In [1]:
#Importing Libiraries
from ar_corrector.corrector import Corrector
import numpy as np
import pandas as pd
from pandas import read_csv
from camel_tools.utils.normalize import normalize_alef_maksura_ar
from camel_tools.utils.normalize import normalize_alef_ar
from camel_tools.utils.normalize import normalize_teh_marbuta_ar

In [2]:
# Read DataSet
url='C:\\Users\\H-P\\ema.csv'
df = read_csv(url, encoding='utf-8-sig')
df.shape

(6172, 9)

In [3]:
df.head(10)

Author  \
0  الكاتب سليمان بن ناصر العلوان   
1  الكاتب سليمان بن ناصر العلوان   
2  الكاتب سليمان بن ناصر العلوان   
3  الكاتب سليمان بن ناصر العلوان   
4  الكاتب سليمان بن ناصر العلوان   
5  الكاتب سليمان بن ناصر العلوان   
6  الكاتب سليمان بن ناصر العلوان   
7      الكاتب مصطفى صادق الرافعي   
8      الكاتب مصطفى صادق الرافعي   
9      الكاتب مصطفى صادق الرافعي   

                                               title  \
0                                   شرح بلوغ المرام    
1                            حكم قراءة الجنب للقرآن    
2                          دعنا نمت حتى ننال شهادةً    
3                    احـــذروا الســحــر والســحـرة    
4                                      فتاوى الصيام    
5                                  الأدلة والبراهين    
6                                    الأمالي المكية    
7                   أوراق الورد  لمصطفى صادق الرافعي   
8   رسائل الأحزان في فلسفة الجمال والحب  لمصطفى ص...   
9               تحت راية القران  لمصطفى صادق الرافعي   

                                         description language  pages  \
0   كتاب شرح بلوغ المرام   كتاب شرح بلوغ المرام  ...     عربي  1041    
1   كتاب حكم قراءة الجنب للقرآن   كتاب حكم قراءة ...     عربي    22    
2   كتاب دعنا نمت حتى ننال شهادةً   كتاب دعنا نمت...     عربي    13    
3   كتاب احـــذروا الســحــر والســحـرة   كتاب اح...     عربي     4    
4   كتاب فتاوى الصيام   كتاب فتاوى الصيام  للكاتب...     عربي   276    
5   كتاب الأدلة والبراهين   كتاب الأدلة والبراهين...     عربي    26    
6   كتاب الأمالي المكية   كتاب الأمالي المكية  لل...     عربي    55    
7   كتاب أوراق الورد  لمصطفى صادق الرافعي  كتاب أ...     عربي   259    
8   كتاب رسائل الأحزان في فلسفة الجمال والحب  لمص...     عربي   185    
9   كتاب تحت راية القران  لمصطفى صادق الرافعي  كت...     عربي   312    

             publishing_house                      size       category  \
0  دار الإيمان للنشر والتوزيع             8.14 ميغابايت        اسلامية   
1  دار الإيمان للنشر والتوزيع  368.5 كيلو بايت ميغابايت        اسلامية   
2  دار الإيمان للنشر والتوزيع             1.66 ميغابايت        اسلامية   
3  دار الإيمان للنشر والتوزيع   31.5 كيلو بايت ميغابايت        العقيدة   
4  دار الإيمان للنشر والتوزيع             4.28 ميغابايت        اسلامية   
5  دار الإيمان للنشر والتوزيع  144.5 كيلو بايت ميغابايت        اسلامية   
6  دار الإيمان للنشر والتوزيع  199.5 كيلو بايت ميغابايت        اسلامية   
7                         NaN             3.44 ميغابايت   الأدب العربي   
8                  دار الهلال                2 ميغابايت   الأدب العربي   
9             المكتبة العصرية              8.5 ميغابايت   الأدب العربي   

                                                 url  
0  https://www.arab-books.com/books/%d9%83%d8%aa%...  
1  https://www.arab-books.com/books/%d9%83%d8%aa%...  
2  https://www.arab-books.com/books/%d9%83%d8%aa%...  
3  https://www.arab-books.com/books/%d9%83%d8%aa%...  
4  https://www.arab-books.com/books/%d9%83%d8%aa%...  
5  https://www.arab-books.com/books/%d9%83%d8%aa%...  
6  https://www.arab-books.com/books/%d9%83%d8%aa%...  
7  https://www.arab-books.com/books/%d9%83%d8%aa%...  
8  https://www.arab-books.com/books/%d9%83%d8%aa%...  
9  https://www.arab-books.com/books/%d9%83%d8%aa%...

In [4]:
# Normalization For Text
for i in range(len(df['title'])):
    sent_norm = normalize_alef_ar(df['title'][i])
    sent_norm = normalize_alef_maksura_ar(sent_norm)
    sent_norm = normalize_teh_marbuta_ar(sent_norm)
    print(sent_norm)
df['category'] = df['category'].fillna("")
for i in range(len(df['category'])):
    sent_norm = normalize_alef_ar(df['category'][i])
    sent_norm = normalize_alef_maksura_ar(sent_norm)
    sent_norm = normalize_teh_marbuta_ar(sent_norm)
    print(sent_norm)

 شرح بلوغ المرام 
 حكم قراءه الجنب للقران 
 دعنا نمت حتي ننال شهادهً 
 احـــذروا الســحــر والســحـره 
 فتاوي الصيام 
 الادله والبراهين 
 الامالي المكيه 
 اوراق الورد  لمصطفي صادق الرافعي
 رسائل الاحزان في فلسفه الجمال والحب  لمصطفي صادق الرافعي
 تحت رايه القران  لمصطفي صادق الرافعي
 حديث القمر  لمصطفي صادق الرافعي
 كلمه وكليمه  لمصطفي صادق الرافعي
 اعجاز القران والبلاغه النبويه  لمصطفي صادق الرافعي
 السحاب الاحمر  لمصطفي صادق الرافعي
 ديوان الرافعي ج2  لمصطفي صادق الرافعي
 ديوان الرافعي ج1  لمصطفي صادق الرافعي
 تاريخ اداب العرب ج3  لمصطفي صادق الرافعي
 تاريخ اداب العرب ج2  لمصطفي صادق الرافعي
 تاريخ اداب العرب ج1  لمصطفي صادق الرافعي
 السمو الروحي الاعظم  لمصطفي صادق الرافعي
 شرح العقيده الواسطيه ج1 
 وحي القلم ج3  لمصطفي صادق الرافعي
 وحي القلم ج2  لمصطفي صادق الرافعي
 وحي القلم ج1  لمصطفي صادق الرافعي
 التبيان في شرح نواقض الاسلام 
 اسئله عن صحه بعض الاحاديث 
 الفوائد والمعاني 
 بدائع الحكم من وحي القلم  لمصطفي صادق الرافعي
 المنتقي من مراقي السعود 
 من قصص التاريخ  لمصطفي صادق الرا

 سر الاب براون 37 
 سر الاب براون 38 
 سر الاب براون 39 
 سر الاب براون 40 
 سر الاب براون 41 
 سر الاب براون 42 
 فضيحه الاب براون 43 
 فضيحه الاب براون 44 
 فضيحه الاب براون 45 
 فضيحه الاب براون 46 
 فضيحه الاب براون 47 
 فضيحه الاب براون 48 
 فضيحه الاب براون 49 
 فضيحه الاب براون 50 
 فضيحه الاب براون 51 
 عجله الحظ 
 مغامرات الدكتور ثورندايك 
 المحقق الخاص 
 مجلس العداله 
 القفل العجيب 
 رجال العداله الاربعه 
 الصحفيه جيني باكستر 
 مشاهير النساء المسلمات 
 الخلاصه في حياه الانبياء 
 لغز البورتريه الكبير وقصص اخري 
 رجال عداله قرطبه 
 دفتر قضايا دكتور ثورندايك 
 قانون رجال العداله الاربعه 
 معالم عصر الخلفاء الراشدين 
 قضايا جون ثورندايك 
 المحققه  اندرو فورستر 
 عين اوزيريس 
 عوده رجال العداله الثلاثه 
 تحفه الاديب في نحاه مغني اللبيب 
 البدور السافره في احوال الاخره 
 صحيح البخاري – المغازي  للالباني
 تصحيح حديث افطار الصائم  للالباني
 النكت علي نزهه النظر  للالباني
 فتاوي رمضانيه 2  للالباني
 فتاوي رمضانيه  للالباني
 صحيح السيره النبويه  للالباني
 موافقه المبطن المخبر  للالباني

تفسير سوره الانسان لابن كثير 
تفسير سوره المرسلات لابن كثير 
تفسير سوره النبا لابن كثير 
تفسير سوره النازعات لابن كثير 
تفسير سوره عبس لابن كثير 
تفسير سوره التكوير لابن كثير 
تفسير سوره الانفطار لابن كثير 
تفسير سوره المطففين لابن كثير 
تفسير سوره الانشقاق لابن كثير 
تفسير سوره البروج لابن كثير 
تفسير سوره الطارق لابن كثير 
تفسير سوره الاعلي لابن كثير 
تفسير سوره الغاشيه لابن كثير 
تفسير سوره الفجر لابن كثير 
 عنايه الله بنبيه في القران الكريم 
 فوائد ولطائف من سيره سليمان 
 خطوره التعايش بين الطاعه والمعصيه 
تفسير سوره الاحقاف لابن كثير 
 100فائده من العلامه الشيخ ابن عثيمين 
 100 فائده في الصوم 
تفسير سوره الجاثيه لابن كثير 
 لسان واذنان 
 احكام نزول المطر 
تفسير سوره الدخان لابن كثير 
 مواجهات من اجل التوحيد 
 العباده في وقت الفتن 
 لما طغي الماء 
تفسير سوره الزخرف لابن كثير 
 اسرع الاعضاء حركه 
 محاضره هيبه الاذان 
تفسير سوره الشوري لابن كثير 
تفسير سوره البلد لابن كثير 
تفسير سوره الشمس لابن كثير 
تفسير سوره الليل لابن كثير 
تفسير سوره الضحي لابن كثير 
تفسير سوره الشرح لابن كثير 

 حول العلم والعمل 
 فتوه العطوف 
 حول الثقافه و التعليم 
 شهر العسل 
 حول التدين و التطرف 
 اساتذتي 
 رحله ابن فطومه 
 امام العرش 
 كيف يتعلم المبرمج بشكل صحيح 
ورق الدكتور ناجي فسيولوجي ANS
 الباقي من الزمن ساعه 
ورق اسئله MCQ الدكتور ناجي CVS
ورق اسئله MCQ الدكتور ناجي ANS2
ورق اسئله MCQ الدكتور ناجي ANS1
ورق اسئله MCQ الدكتور ناجي Hormones
ورق اسئله MCQ الدكتور ناجي Exitable Tissue
ورق اسئله MCQ الدكتور ناجي Body Temprature
ورق اسئله MCQ الدكتور ناجي Endocrine3
ورق اسئله MCQ الدكتور ناجي Endocrine2
ورق اسئله MCQ الدكتور ناجي Endocrine1
ورق اسئله MCQ الدكتور ناجي GIT2
 رابيدوس 
 قلب الليل 
 دنيا الله 
 اهل الهوي 
سوره البقره  خط واضح | تفسير سوره البقره
 الجريمه لنجيب محفوظ 
 صباح الورد 
 عبث الاقدار 
ورق اسئله MCQ الدكتور ناجي GIT1
ورق اسئله MCQ الدكتور ناجي Respiration2
ورق اسئله MCQ الدكتور ناجي Respiration1
ورق اسئله MCQ الدكتور ناجي CNS
ورق اسئله MCQ الدكتور ناجي Kidney
ورق اسئله MCQ الدكتور ناجي Body Fluids
ورق الدكتور ناجي فسيولوجي Biophysics
ورق الدكتور ناجي فسيولوجي Introduc

 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
 اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده
العقيده
 الفلسفه والمنطق
 اصول الفقه
 اصول الفقه
 اصول الفقه
العقيده
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده
العقيده  اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
العقيده  اسلاميه
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 الاطفال
 ا

 الادب العربي
 الادب العربي
 الادب العربي
 الادب العربي
 الادب العربي
 الادب العربي  التاريخ  التاريخ الحديث
 الادب العربي  التاريخ
العقيده
 تفاسير  علوم القران
الحديث العقيده  فقه المراه المسلمه
العقيده
العقيده  اسلاميه
 اسلاميه
 فتاوي اسلاميه
 فتاوي اسلاميه
 فتاوي اسلاميه
العقيده  فتاوي اسلاميه
 الادب العربي
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
 الادب العربي
 الادب العربي
 الادب العربي
 الادب العربي  و دواوين الشعر العربي
 الادب العربي
 الادب العربي
 متنوعه
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي
 التاريخ الاسلامي  التاريخ القديم
 التاريخ الاسلامي
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
 الادب العربي  الفلسفه والمنطق
روايات بوليسيه
 الادب العربي  الفلسفه والمنطق
 الادب العربي  التاريخ
 اسلاميه  الادب العربي
 اسلاميه
 اسلاميه
 اسلاميه
 اسلاميه
 اسل

 روايات عربيه
 روايات عربيه
 روايات عربيه
العقيده
 الفلسفه والمنطق  المسرحيات العالميه المترجمه  مسرحيات عربيه
 المسرحيات العالميه المترجمه  روايات عربيه  مسرحيات عربيه
 المسرحيات العالميه المترجمه  روايات عربيه  مسرحيات عربيه
العلوم السياسيه والاستراتيجيه
الادب
 روايات عربيه
 روايات عربيه
 روايات عربيه
 روايات عربيه
 روايات عربيه
الادب
الادب
 روايات عربيه
 روايات عربيه
 روايات عربيه
 روايات عربيه
 روايات عربيه
 روايات عربيه
العقيده
الادب
الادب
الادب
الادب
الادب
الادب
الادب
 المسرحيات العالميه المترجمه  روايات عربيه  مسرحيات عربيه
الادب  المسرحيات العالميه المترجمه
 مسرحيات عربيه  روايات عربيه
العقيده
العقيده
العقيده
 المسرحيات العالميه المترجمه  روايات عربيه
 مسرحيات عربيه  روايات عربيه
الادب  الادب العربي
القران الكريم
العقيده
 روايات عربيه
العقيده
العقيده
 روايات عربيه
 روايات عربيه
 التاريخ  التاريخ الاسلامي  التاريخ القديم
 الادب العربي  التاريخ الحديث
 الادب
 التاريخ الحديث  التاريخ القديم
الادب
 اسلاميه العقيده
 روايات عربيه
 روايات عربيه
 روايات عربيه
علوم القران الكريم والسنه 

In [ ]:
# AutoCorrect For DataSet
corr = Corrector()
df['category'] = df['category'].fillna("")
for i in range(len(df['category'])):
    print(corr.contextual_correct(df['category'][i]))
for i in range(len(df['title'])):
        print(corr.contextual_correct(df['title'][i])) 

In [5]:
for i in range(len(df['description'])):
    sent_norm = normalize_alef_ar(df['description'][i])
    sent_norm = normalize_alef_maksura_ar(sent_norm)
    sent_norm = normalize_teh_marbuta_ar(sent_norm)
    print(sent_norm)

 كتاب شرح بلوغ المرام   كتاب شرح بلوغ المرام  للكاتب سليمان بن ناصر العلوان كتاب شرح بلوغ المرام  للكاتب سليمان بن ناصر العلواني استخدم فيه الكاتب سليمان بن ناصر اساليب ومعاني واضحه لتيسير الفهم علي القراء وتوصيل جميع المفاهيم بطريقه واضحه لافاده جميع الفئات من قراءه كتبه وسيتضح لكم ذلك من خلال قرائتكم لكل كتاب سنقوم بنشره لكم. فهذا كتاب البلوغ للحافظ ابن حجر مشتمل علي ادله الاحكام وقد ذكر الحافظ رحمه الله عليه بانه حرره تحريراً بالغاً ليكون عمده للمبتديء وتنبيهاً للمنتهي. كتاب شرح بلوغ المرام 
 كتاب حكم قراءه الجنب للقران   كتاب حكم قراءه الجنب للقران  للكاتب سليمان بن ناصر العلوان كتاب حكم قراءه الجنب للقران  للكاتب سليمان بن ناصر العلواني استخدم فيه الكاتب سليمان بن ناصر اساليب ومعاني واضحه لتيسير الفهم علي القراء وتوصيل جميع المفاهيم بطريقه واضحه لافاده جميع الفئات من قراءه كتبه وسيتضح لكم ذلك من خلال قرائتكم لكل كتاب سنقوم بنشره لكم. ان تصنيف الاجزاء الحديثه والفقهيه واللغويه وغيرها في سائر العلوم والفنون لها ثمار كبيره وفيها فوائد جليله يستطيع المؤلف من خلالها الالمام بمعظم مسائل

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [6]:
df.isnull().sum()

Author                0
title                 0
description           2
language              0
pages                62
publishing_house     50
size                115
category              0
url                   0
dtype: int64

In [7]:
# Check For Null Values
df.isnull()

Author  title  description  language  pages  publishing_house   size  \
0      False  False        False     False  False             False  False   
1      False  False        False     False  False             False  False   
2      False  False        False     False  False             False  False   
3      False  False        False     False  False             False  False   
4      False  False        False     False  False             False  False   
...      ...    ...          ...       ...    ...               ...    ...   
6167   False  False        False     False  False             False  False   
6168   False  False        False     False  False             False  False   
6169   False  False        False     False  False             False  False   
6170   False  False        False     False  False             False  False   
6171   False  False        False     False  False             False  False   

      category    url  
0        False  False  
1        False  False  
2        False  False  
3        False  False  
4        False  False  
...        ...    ...  
6167     False  False  
6168     False  False  
6169     False  False  
6170     False  False  
6171     False  False  

[6172 rows x 9 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6172 entries, 0 to 6171
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Author            6172 non-null   object
 1   title             6172 non-null   object
 2   description       6170 non-null   object
 3   language          6172 non-null   object
 4   pages             6110 non-null   object
 5   publishing_house  6122 non-null   object
 6   size              6057 non-null   object
 7   category          6172 non-null   object
 8   url               6172 non-null   object
dtypes: object(9)
memory usage: 434.1+ KB


In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

Author              0
title               0
description         0
language            0
pages               0
publishing_house    0
size                0
category            0
url                 0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
desc = df['description']
X = (desc)
y= df['category']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
y_train.value_counts(), y_test.value_counts()

( اسلامية                                                                            1009
 روايات بوليسية                                                                       527
  روايات عربية                                                                        430
  الأطفال                                                                             210
  الأدب العربي                                                                        165
                                                                                     ... 
  التاريخ الإسلامي  الأدب العربي                                                        1
 التنمية الذهنية  متنوعة                                                                1
 الأدب  الأدب العربي  التاريخ الحديث                                                    1
 الأدب  الفلسفة والمنطق  المسرحيات العالمية المترجمة  روايات عربية  مسرحيات عربية       1
 الثقافة العامة العلوم السياسية والاستراتيجية                                           1
 Name: cat

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [14]:
text_clf_svm = Pipeline([('tfidf',TfidfVectorizer()),
                       ('svc', LinearSVC()),])
text_clf_svm.fit(X_train, y_train)
predictions = text_clf_svm.predict(X_test)
print(text_clf_svm.score(X_train, y_train))

0.9872278056951423


In [15]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.accuracy_score(y_test, predictions))

[[6 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 8]]
0.7715481171548118


In [16]:
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.accuracy_score(y_test, predictions))

[[6 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 8]]
0.7715481171548118


In [17]:
text_clf_svm.predict(["كتاب طريق المجد للشباب"])

array(['الأدب'], dtype=object)

In [18]:
text_clf_svm.predict(["كتاب خديعة التطور"])

array([' الفلسفة والمنطق'], dtype=object)

In [19]:
text_clf_svm.predict(["'نظرة ثاقبة في التجارة', 'تحقيق حسن حسني عبد الوهاب', 'يتعمق الجاحظ في هذا الكتاب في كل أمور التجارة في عصره. كالعادة ، يذكر الأمور القصصية بأسلوب فكاهي أدبي كان يميزه. يروي غرابة البضائع والسلع الثمينة مثل المصوغات النفيسة ، والمعادن النفيسة كالذهب والفضة ، والعطور والعطور الفاخرة ، وحتى العبيد والخادمات ، والاختلافات بين أجناسهم التي تحدد أسعارها ، والطيور الجارحة ، الملابس والحيوانات والفرائس. يهدف إلى جعل كتابه مفيدًا لأولئك الذين يرغبون في معرفة ظروف السوق في ذلك الوقت ، والتعلم أكثر من تجارب الخبراء المخضرمين وخبراء التجارة. وهذا ملخص كتاب التبصر بالتجارة"])

array([' متنوعة'], dtype=object)

In [20]:
text_clf_svm.predict(["'دليل الملاعق الفضية', 'روبرت بار', 'ترجمة زينب عاطف ، مراجعة محمد فتحي خضر', 'أقام السيد بنثام جيبس حفل عشاء لمجموعة من أصدقائه ، وسرقت منه فواتير المائة جنيه. يذهب إلى المحقق الخاص فالمونت لعرض القضية ويطلب منه المساعدة في استعادة أمواله بناءً على توصية صديقه العزيز. يستبعد فالمونت إمكانية دخول لص من الخارج وسرقة الأموال ، فتتحول شكوكه إلى المدعوين. في البداية كان يشك في داكر ، وهو صديق مقرب من جيبس. كان يعلم أنه بحاجة إلى المال ، لكن خدعة الملاعق الفضية كشفت عن مشتبه به آخر لم يكن يتوقعه. ما سر تلك الحيلة؟ كيف تم الكشف عن اللص الحقيقي؟ اقرأ القصة لتعرف الأسرار المثيرة لهذه القضية.', 'وهذا ملخص رواية دليل الملاعق الفضية', 'احصل على اخر الكتب مجانا علي قناة التليجرام مباشرةً'"])

array(['روايات بوليسية'], dtype=object)