In [22]:
#Importing Libiraries
from ar_corrector.corrector import Corrector
import numpy as np
import pandas as pd
from pandas import read_csv
from camel_tools.utils.normalize import normalize_alef_maksura_ar
from camel_tools.utils.normalize import normalize_alef_ar
from camel_tools.utils.normalize import normalize_teh_marbuta_ar

In [23]:
# Read DataSet
url='D:\en.csv'
df = read_csv(url, encoding='utf-8-sig')
df.shape

(5940, 5)

In [24]:
df.head()

Author                                  Title  \
0  الكاتب هارون يحيىالكاتب هارون يحيى  كتاب هدم نظرية التطور في عشرين سؤالا    
1  الكاتب هارون يحيىالكاتب هارون يحيى                        كتاب فن التأمل    
2  الكاتب هارون يحيىالكاتب هارون يحيى                    كتاب الأمم البائدة    
3  الكاتب هارون يحيىالكاتب هارون يحيى                كتاب المعجزات القرآنية    
4  الكاتب هارون يحيىالكاتب هارون يحيى                     كتاب خديعة التطور    

                                        Link for PDF             Category  \
0  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
1  https://www.arab-books.com/books/%d9%83%d8%aa%...     كتب الأدب العربي   
2  https://www.arab-books.com/books/%d9%83%d8%aa%...       الثقافة العامة   
3  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
4  https://www.arab-books.com/books/%d9%83%d8%aa%...  كتب الفلسفة والمنطق   

   Number Of Pages  
0              154  
1               68  
2              162  
3               99  
4              258

In [25]:
# AutoCorrect For DataSet
corr = Corrector()
for i in range(len(df['Category'])):
    print(corr.contextual_correct(df['Category'][i]))
for i in range(len(df['Title'])):
        print(corr.contextual_correct(df['Title'][i]))  

كتب اسلامية
كتب الأدب العربي
الثقافة العامة
كتب اسلامية
كتب الفلسفة والمنطق
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب أدب السجون
كتب الأدب العربي
كتب الأدب العربي
العلوم السياسية والاستراتيجية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
الأدب
الأدب
الأدب
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلام

كتب الأطفال
كتب الأطفال
كتب علم النفس
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب علم النفس
كتب الأطفال
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب الأطفال
الأدب
كتب الأطفال
الأدب
كتب الأطفال
الأدب
الأدب
كتب الأطفال
الأدب
الأدب
كتب الأطفال
الأدب
كتب الأطفال
الأدب
كتب الأطفال
الأدب
الأدب
كتب الأطفال
الأدب
الأدب
الأدب
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأدب العربي
كتب الأطفال
كتب اسلامية
كتب الأطفال
كتب الأطفال
العقيدة
كتب الأطفال
العقيدة
كتب الأطفال
العقيدة
العقيدة
كتب الأطفال
العقيدة
كتب الأطفال
كتب اسلامية
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
العقي

كتاب
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب روايات عربية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتاب
كتب اسلامية
كتب متنوعة
العقيدة
العقيدة
العقيدة
العلوم السياسية والاستراتيجية
تفاسير
العقيدة
العقيدة
العقيدة
العقيدة
كتب التاريخ
روايات بوليسية
روايات بوليسية
كتب روايات عربية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
كتاب
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اس

كتاب
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
روايات بوليسية
الثقافة العامة
روايات بوليسية
الثقافة العامة
الثقافة العامة
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
علوم القرآن الكريم والسنة النبوية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
ر

كتاب
كتب اسلامية
كتاب
كتب اسلامية
كتب اسلامية
الأدب
كتب اسلامية
كتب اسلامية
كتب اسلامية
الطب
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
كتب الأدب العربي
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب

كتاب
رمضانيات
كتب أصول الفقه
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
الأدب
رمضانيات
رمضانيات
كتب اسلامية
رمضانيات
الثقافة العامة
رمضانيات
رمضانيات
رمضانيات
رمضانيات
العلوم السياسية والاستراتيجية
رمضانيات
كتب روايات عربية
كتب روايات عربية
رمضانيات
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب القصص القصيرة
كتب أصول الفقه
رمضانيات
الأدب
كتب أصول الفقه
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتب أدب الرحلات
الأدب
كتب أدب الرحلات
الثقافة العامة
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتب الأدب العربي
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
كتاب
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
كتب روايات عربية
رمضانيات
رمضانيات
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب رو

روايات بوليسية
روايات بوليسية
روايات بوليسية
قصص أطفال
قصص أطفال
قصص أطفال
قصص أطفال
قصص أطفال
قصص أطفال
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
كتب و دواوين الشعر العربي
كتب و دواوين الشعر العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب و دواوين الشعر العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب التاريخ الحديث
كتب التاريخ القديم
كتب التاريخ الحديث
كتب التاريخ القديم
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب الأدب العربي
كتب التاريخ الإسلامي
كتب التاريخ
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب التاريخ
كتب اسلامية
كتب التاريخ القديم
كتب الأدب العربي
كتب التاريخ القديم
كتب التاريخ الإسلامي
كتب الأدب العربي
كتب التاريخ الإسلامي
كتب روايات عربية
ك

كتاب من أعلام المسلمين مشاهيرهم
كتاب رجال الفكر والدعوة ج 3-4
كتاب رجال الفكر والدعوة ج 1-2
كتاب الحضارة الغربية
كتاب نصائح وتوجيهات
كتاب عن وطن لحم ودم للكاتب أدهم الشرقاوي
كتاب خربشات خارجة عن القانون للكاتب أدهم الشرقاوي
كتاب حديث الصباح للكاتب أدهم الشرقاوي
كتاب قصص النبيين للأطفال
كتاب الطريق إلى المدينة
كتاب المرتضى
كتاب النبوة والأنبياء
كتاب من الجاهلية إلى الإسلام
كتاب نفحات الإيمان
كتاب مسئولية العلماء في الأوضاع المتغيرة
كتاب موقف العالم الإسلامي
كتاب من نهر كابل إلى نهر اليرموك
كتاب صورتان متضادتان
كتاب الطريق إلى السعادة
كتاب البلاغة تطور وتاريخ
كتاب الحب العذرى عند العرب
كتاب البحث الأدبي
كتاب جواهر القلوب للكاتب أبو حامد الغزالي
كتاب منهاج العابدين إلى الجنة للكاتب أبو حامد الغزالي
كتاب شوقى شاعر العصر الحديث
كتاب تهذيب المهلكات والمنجزات للكاتب أبو حامد الغزالي
كتاب مجربات الغزالي في الطب الروحاني للكاتب أبو حامد الغزالي
كتاب الأطفال للكاتب أبو حامد الغزالي
كتاب خافية الحروف الثمانية والعشرين للكاتب أبو حامد الغزالي
كتاب التفكر في خلق الله للكاتب أبو حامد الغزالي
كتاب ال

كتاب البلدان والعرفان والعصيان والجولان
كتاب فلسفة الجد والهزل
كتاب تهذيب الحيوان للجاحظ
كتاب القول في البغال
كتاب العثمانية للجاحظ
كتاب الحنين إلى الأوطان
كتاب المحاسن والأجداد
كتاب رسائل الجاحظ
كتاب الحيوان المجلد الثالث
كتاب البيان والتبيين المجلد الأول
رواية البخلاء نسخة اخري
كتاب البيان والتبيين المجلد الرابع
كتاب البيان والتبيين المجلد الثالث
كتاب الحيوان المجلد الثاني
كتاب الحيوان المجلد الأول
كتاب الحيوان للجاحظ
رواية البخلاء كتابة جديدة
كتاب البيان والتبيين المجلد الثاني
كتاب مقدمة البيان والتبيين
كتاب إزالة أسباب الخذلان
كتاب ماذا خسر العالم بانحطاط المسلمين
كتاب المصباح الفضي
كتاب لصوص نيويورك
كتاب أرسين لوبين المجرم
كتاب الدائرة السوداء
كتاب أرسين لوبين الشريف pdf
كتاب سر عقد اللؤلؤ
كتاب كنوز أرسين لوبين
كتاب إنتقام ميت
كتاب جوهرة التاج
كتاب أرسين لوبين في موسكو
كتاب البيت الأسود
كتاب الإنذار
كتاب السهم القاتل
كتاب الخطر الأصفر
كتاب الجرائم الثلاثة
كتاب البرنس أرسين لوبين
كتاب السوق السوداء
كتاب المسلة الجوفاء
كتاب الرهان
كتاب الجثة المفقودة
كتاب ميزان العمل للكاتب أبو حامد

مجلة ميكي والسيارة
مجلة ميكي صاحب الفضل
مجلة ميكي العدد 871
مجلة ميكي العدد 870
مجلة ميكي العدد 812
مجلة ميكي العدد 796
مجلة ميكي العدد 783
مجلة ميكي العدد 771
مجلة ميكي العدد 752
مجلة ميكي العدد 738
مجلة ميكي العدد 730
مجلة ميكي العدد 691
مجلة ميكي العدد 689
مجلة ميكي العدد 688
مجلة ميكي العدد 639
مجلة ميكي العدد 580
مجلة ميكي العدد 566
مجلة ميكي العدد 564
مجلة ميكي العدد 336
مجلة خطوط العدد 706
كتاب الكافي في اللغة
كتاب ميزان الذهب في صناعة شعر العرب
كتاب تعلم لغة جديدة بسرعة وسهولة
كتاب الحروف اللاتينية لكتابة العربية
كتاب جواهر البلاغة
كتاب الإبداع الفكري والخصوصية الحضارية
كتاب اجتهاد الرسول وقضائه
كتاب صيحة نذير من فتنة التكفير
كتاب الشيخ المراغي والإصلاح الديني
كتاب الإصلاح بالإسلام
كتاب خطر النزعة التاريخية على ثوابت الإسلام
كتاب لتحيا اللغة العربية يسقط سيبويه
كتاب مفاتيح العلوم
كتاب السر في العين
كتاب السر ف القبعة
كتاب اللص الظريف
كتاب إسلامية المعرفة ماذا يعني
كتاب في الإصلاح الفكري والتربوي الإلهيات
كتاب مأزق المسيحية والعلمانية في أوروبا
كتاب الإسلام وضرورة التغيير
كتاب ع

رواية مغامرات الكبيري فين
رواية حول العالم في ما يوما
كتاب تاريخ مصر من الفتح العثماني إلى قبيل الوقت الحاضر
رواية تجربة الدكتور أو
كتاب مصر في مطلع القرن التاسع عشر ١٨٠١–١٨١١م الجزء الثاني
كتاب أزمنة الثقافة الإيرانية معايشة من الداخل الجزء الأول
رواية الأمير والفقير
كتاب اصنام الكتابات
كتاب تاريخ الصلاة في الإسلام نسخة سالم الدليمي
كتاب مصر في مطلع القرن التاسع عشر الجزء الأول
كتاب ابو الهول
كتاب موسوعة مصر القديمة الجزء السابع عشر
رواية عشرون ألف فرصة تحت الماء
رواية شتاء وسط الجليد
رواية مغامرات توم سير
كتاب الصراع بين البورجوازية والإقطاع ١٧٨٩–١٨٤٨م المجلد الثالث
رواية في العام 2899
كتاب الصراع بين البورجوازية والإقطاع ١٧٨٩–١٨٤٨م المجلد الثاني
رواية رحلة على متن منطاد
كتاب الصراع بين البورجوازية والإقطاع ١٧٨٩–١٨٤٨م المجلد الأول
كتاب مصر في مطلع القرن التاسع عشر ١٨٠١–١٨١١م الجزء الثالث
كتاب المانيا النازية
رواية السيد ماريوس
كتاب مفهوم المنهج العلمي
كتاب فلسفة كارل بوبر
كتاب مشكلة العلوم الإنسانية
كتاب فلسفة العلم في القرن العشرين
كتاب ركائز في فلسفة السياسة
كتاب بحوث في تاريخ العل

مجلة ذكرني
كتاب تهذيب مدارج السالكين
مجلة ميكي العدد 131
كتاب مدارج السالكين
كتاب الحلقة المفقودة
كتاب الأمثال في القرآن
مجلة ميكي العدد 181
كتاب الفوائد
مجلة مواطن بطيء نموذجي
مجلة كل سنة وانت طيب
مجلة سوبر ميكي قرش الحظ
مجلة خطوط وميكي ماذا لو
مجلة خطوط وميكي ماذا حدث
مجلة خطوط وميكي دوت كوم
كتاب مراجع الشخصية للكاتب سيغموند فرويد
كتاب زاد المعاد في هدي خير العباد
كتاب ما فوق المبدأ واللذة للكاتب سيغموند فرويد
كتاب التحليل النفسي الهستيريا للكاتب سيغموند فرويد
كتاب علم نفس الجماهير للكاتب سيغموند فرويد
كتاب اليوم والحرام للكاتب سيغموند فرويد
كتاب الحلم وتأويله للكاتب سيغموند فرويد
كتاب القرآن يتحدى
كتاب العلمانية بين الغرب والاسلام
كتاب الغريزة والثقافة للكاتب سيغموند فرويد
كتاب لمرتين لإلياس أبو شبكة
كتاب غلواء لإلياس أبو شبكة
كتاب طاقات زهور
كتاب الحياة الجنسية للكاتب سيغموند فرويد
كتاب مستقبل وهم للكاتب سيغموند فرويد
كتاب إبليس في التحليل النفسي للكاتب سيغموند فرويد
كتاب التحليل النفسي لها الأطفال للكاتب سيغموند فرويد
كتاب أفكار لأزمنة الحرب والموت للكاتب سيغموند فرويد
كتاب التصعي

كتاب الإسلام أوضاعنا السياسية
كتاب جزيرة روس
كتاب موسوعة الخطب المخبرية (2)
كتاب ملوك العرب
كتاب المهذب في شرح المائة النسائية
كتاب تهذيب صحيح ابن حبان (13)
كتاب تهذيب الأدب المفرد للبخاري
كتاب الإيمان بالملائكة وبين صفاتهم
كتاب دروس وعبر من حياة شهداء الثورة السورية
كتاب هل يعتبر الفراعنة بمصرع من سبقهم
كتاب الخلاصة في أصول التربية الإسلامية
كتاب تحقيق الهداية في النحو
كتاب الخلاصة في حكم سب الصحابة
كتاب الخلاصة في حكم الاستعانة بالكفار في القتال
كتاب الخلاصة في أحكام التمرس
كتاب الخلاصة في أحكام الانتحار
كتاب الميسر في الأحاديث القدسية
كتاب الإسلام بين جهل أبنائه وعجز علمائه
كتاب مشروعية المشاركة
كتاب صحيفة همام بن منبه
كتاب تهذيب الحرية أو الطوفان
كتاب الخلاصة في فقه الصلاة على المذهب الشافعي
كتاب مفهوم الولاء والبراء في القرآن والسنة
كتاب الأربعون الطبية
كتاب موسوعة الأسرة المسلمة
كتاب عائلة أونا
كتاب طيش الشباب
كتاب سطح خزنت أرجوكم
كتاب رحلة البحث عن الكنز
كتاب تحذير عاصفة
كتاب تبادلية والتر ديزني
كتاب صفات البيت المسلم
كتاب ترجمة الأئمة الأربعة
كتاب الأربعون الاجتماعية
كتاب الخلا

كتاب فقه الصلاة وأحكامها وفتاواها
كتاب مقامات السيوطي
كتاب الروض الأنيق في فضل الصديق
كتاب إعلام الأريب
كتاب روسو مقدمة قصيرة جدا
كتاب التراث الكلاسيكي
كتاب النوم مقدمة قصيرة جدا
كتاب جون رينارد كينز
كتاب جون لوك
كتاب الدودة والثعبان
كتاب مأساة زينب
كتاب الفارس الجميل
كتاب إمبراطورية في المزاد
كتاب قصر الهودج
كتاب الارستقراطية مقدمة قصيرة جدا
كتاب نظرية الالعاب
كتاب الديناصورات مقدمة قصيرة جدا
كتاب اليوتوبيا مقدمة قصيرة جدا
كتاب رولان بارت
كتاب الانسانية مقدمة قصيرة جدا
كتاب علم الأحياء النهائي
كتاب التطور مقدمة قصيرة جدا
كتاب الدعائية والسريالية
كتاب توفيق مقدمة قصيرة جدا
كتاب النظرية النقدية
كتاب الحقيقة مقدمة قصيرة جدا
كتاب تاريخ الطب
الإيمان في صحيح أذكار النوم والاستيقاظ
كتاب الفلسفة الهندية
كتاب البوذية مقدمة قصيرة جدا
كتاب الكواكب مقدمة قصيرة جدا
كتاب علم الاحصاء
كتاب الخيال العلمي
كتاب نظرية الاختيار
كتاب فقه العيدين وأحكامها فتاويها
كتاب أعمال صالحا لدخول الجنات
كتاب العناصر مقدمة قصيرة جدا
كتاب علم التشفير
كتاب جامع المنظومات في ضبط المتشابهات
كتاب من فَضِيلَةً مِنْ فَضَائِلِ

كتاب عقد قبل سنت وجماعة من بين اور اسمه ابدى في الموت
كتاب زكاة بهيمة الأنعام السائمة في ضوء الكتاب والسنة
كتاب السلام في الإسلام
كتاب مجموعة رسائل الإمام الشهيد حسن البنا
كتاب قضيتنا ودعوتنا
كتاب خطابات حسن البنا الشاب إلى أبيه
كتاب الله في العقيدة الإسلامية
كتاب نظرات في كتاب الله
كتاب مذكرات الدعوة والداعية
كتاب نحو بعث جديد
كتاب نظرات في كتاب الله
كتاب ايام من حياتي
رواية المرأة مشكلة صنعها الرجل
رواية خلف أسوار العقل
كتاب الكلمة المقدسة
كتاب فقه الاستغفار
كتاب فقه الحياء
رواية الذين كانوا
رواية قلبي ليس للبيع
رواية الانفجار الحي
كتاب صلاتي حياتي
كتاب القصيدة الذهبية
كتاب رجل لكل العصور ابن تيمية
كتاب الأدب الضائع
كتاب صيحة تحذير وصرخة نذير
كتاب سيدى تحفة
كتاب دفع المال على مشروعية الحجاب الكامل
كتاب ضرورة محو الأمية التربوية
كتاب مالم تقرأه في الكتب عن أسرار المدير لأول مرة
كتاب علو الهمة نسخة اخري
كتاب حرمة أهل العلم
كتاب أدلة تحريم مصافحة الأجنبية النسخة الثانية
كتاب أدلة تحريم مصافحة الأجنبية
كتاب الإعلام بحرمة أهل العلم والإسلام
كتاب مناجاة المحسنين في الخلوات
كتاب تفجيرات لند

كتاب ذكريات صغيرة
كتاب حول التأصيل الإسلامي للعلوم الاجتماعية
كتاب دروس من محنة البوسنة والهرسك
كتاب قضية تحرير المراة
كتاب التطور والثبات في حياة البشرية
رواية الخنجر الفضي
رواية المؤامرة الخفية
كتاب أعماق الخطر
كتاب قراصنة الجو
كتاب عوامل السعة والمرونة في الشريعة الإسلامية للشيخ يوسف القرضاوي
كتاب المحنة في واقع الحركة الإسلامية المعاصرة للشيخ يوسف القرضاوي
كتاب النية والإخلاص للشيخ يوسف القرضاوي
كتاب الصحوة الإسلامية للشيخ يوسف القرضاوي
رواية الرمال المحرقة
كتاب المدخل لدراسة السنة النبوية للشيخ يوسف القرضاوي
كتاب عيون الهلاك
رواية ظل الأرض
رواية أشباح ولكن
كتاب الصراع الشيطاني
كتاب العين الثالثة
كتاب اخر العمالقة
كتاب أقوي رجل في العالم
كتاب الجاسوس الخارق
كتاب الجزيرة الذهبية
كتاب الرجل الثالث
كتاب الرجل الذي سرق الشمس
كتاب القنبلة لمحمود سالم
كتاب القوة الخفية
كتاب المدينة الصامتة
كتاب المغامرون الخمسة والرقم الناقص
كتاب الهدف لا شيء
كتاب 1=4 أو المجهول pdf
كتاب عميلة باراكودا
كتاب سر الغواصة المجهولة
كتاب سر الطائرة المحطمة
كتاب رمال الموت
كتاب رقم 999
كتاب رصاصة واحدة تكفي
كتا

كتاب اسبينوزا لفؤاد زكريا
كراسة شروط مبادرة التمويل العقاري في ما الرسمية كاملة
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية جدا فهرس عام للكتاب للحافظ ابن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ بن كثير
كتاب البداية والنهاية في للحافظ بن كثير
كتاب البداية والنهاية في للحافظ بن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
رواية الغزاة
رواية الانفجار
رواية الخصم الرهيب
كتاب العدو الخارق
كتاب افاق الفلسفة
رواية الكهف
كتاب آراء نقدية في مشكلات الفكر والثقافة
كتاب تاريخ المشرق
كتاب الرق في الإسلام
كتاب زاد في التفسير المستوى الرابع
كتاب زاد في الفقه المستوى الرابع
كتاب زاد في العربية المستوى الرابع
كتاب زاد

كتاب لغز الألف وجهpdf
كتاب لغز حمام السباحةpdf
كتاب لغز الحي الهادئpdf
كتاب لغز سر المجنونpdf
كتاب لغز العصا البيضاءpdf
كتاب لغز نور القمرpdf
كتاب لغز الرسالة المجهولةpdf
كتاب لغز فيلا المعاديpdf
كتاب لغز الخدعة المزدوجةpdf
كتاب لغز السرقة الثانيةpdf
كتاب لغز الراقص الإفريقيpdf
كتاب لغز الجاسوس الترانزستورpdf
كتاب لغز من الماضيpdf
كتاب لغز ثعلب الصحراءpdf
كتاب لغز الزلازل الغامضةpdf
كتاب لغز الدبلوماسي المخطوفpdf
كتاب لغز السائح القصيرpdf
كتاب لغز القارب الفرعونيpdf
كتاب لغز الخطة الرهيبةpdf
كتاب لغز الرسام والكلبpdf
كتاب لغز الزائر الغامضpdf
كتاب لغز مزرعة الرياحpdf
كتاب لغز مغارة الشيطان pdf
كتاب لغز الكلب ذو الرأسين pdf
كتاب جامع المسانيد والسنن مقدمة من للحافظ ابن كثير
كتاب جامع المسانيد والسنن مقدمة من للحافظ ابن كثير
كتاب جامع المسانيد والسنن مقدمة من للحافظ ابن كثير
كتاب جامع المسانيد والسنن مقدمة جدا للحافظ ابن كثير
كتاب جامع المسانيد والسنن مقدمة جدا للحافظ ابن كثير
كتاب جامع المسانيد والسنن جدا للحافظ ابن كثير
كتاب جامع المسانيد والسنن مقدمة جدا لابن كثير
كتاب جامع المسانيد و

رواية الرجل العنكبوت pdf
رواية الأموال السوداء pdf
رواية العدو المجهول pdf
رواية عدو في الفضاء pdf
رواية جزيرة الحيتان pdf
رواية الخدعة الأخيرة pdf
رواية عش النسر pdf
رواية سباق الموت pdf
رواية الدرابيل لمحمود سالم pdf
رواية جزر ساندويتش pdf
رواية سر المخطوفة pdf
رواية الخائن لمحمود سالم pdf
رواية العصفور لمحمود سالم pdf
رواية جبال كليمنجارو pdf
رواية نهايه الخائن pdf
رواية الدليل الأسود pdf
رواية الإغتيال لمحمود سالم pdf
رواية اللص الإلكتروني pdf
رواية طريق الهيروين pdf
رواية الطائرة الخفية pdf
رواية مغامرة في روما pdf
رواية المنطقة المفقوده pdf
رواية مدار السرطان pdf
رواية قنابل الدخان pdf
رواية القصر الأبيض pdf
رواية لغز نور القمر pdf
رواية لغز الفتاه المشلولة pdf
رواية لغز مدينه الآلهه pdf
رواية لغز ورقة الكوتشينغ pdf
رواية لغز عصابة الأشباح pdf
رواية لغز الرساله الطائرة pdf
رواية لغز البحر الميت pdf
رواية لغز الرقم الناقص pdf
رواية لغز وادي المساخيط pdf
رواية لغز عمارة العفاريت pdf
رواية لغز السلعة لمحمود سالم pdf
رواية قطار الجحيم
رواية الرجل الذي يجمع كتب بو
رواية ماتيلدا للكاتب

كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث الجامع الصغير جدا
كتاب جامع الأحاديث الجامع الصغير جدا
كتاب جامع الأحاديث الجامع الصغير جدا
القرآن الكريم الجزء الثلاثون ملون pdf
القرآن الكريم الجزء التاسع والعشرون ملون pdf
القرآن الكريم الجزء الثامن والعشرون ملون pdf
القرآن الكريم الجزء السابع والعشرون ملون pdf
القرآن الكريم الجزء السادس والعشرون ملون pdf
القرآن الكريم الجزء الخامس والعشرون ملون pdf
القرآن الكريم الجزء الرابع والعشرون ملون pdf
القرآن الكريم الجزء الثالث والعشرون ملون pdf
القرآن الكريم الجزء الثاني والعشرون ملون pdf
القرآن الكريم الجزء الحادي والعشرون ملون pdf
القرآن الكريم الجزء العشرون ملون pdf
القرآن الكريم الجزء التاسع عشر مليون pdf
القرآن الكريم الجزء الثامن عشر مليون pdf
القرآن الكريم الجزء السابع عشر مليون pdf
القرآن الكريم الجزء السادس عشر مليون pdf
القرآن الكريم الجزء الخامس عشر مليون pdf
القرآن الكريم الجزء الرابع عشر مليون pdf
القرآن الكريم الجزء الثالث عشر مليون pdf
القرآن الكريم الجزء الثاني عشر مليون pdf
القرآن الكريم الجزء

كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب ألف باء التصميم الداخلي pdf
كتاب المعايير الشرعية للمؤسسات المالية الإسلامية pdf
كتاب الضغط النفسي pdf
كتاب الفوتوشوب خطوة خطوة حتي الإحتراف pdf
كتاب نظم المعلومات الإدارية pdf
كتاب التوحد pdf
كتاب خفايا الدماغ pdf
كتاب تعليم أساسيات الحاسب الآلي pdf
كتاب أصول المحاسبة المالية في pdf
كتاب أصول المحاسبة المالية في pdf
كتاب المحاسبة المالية في
كتاب المعايير المحاسبية الدولية pdf
كتاب محاسبة التكاليف pdf
كتاب مبادئ المحاسبة pdf
كتاب المحاسبة المالية من الألف إلى الياء في pdf
كتاب المغرب الأقصى
كتاب تفسير آيات الربا
رواية عبقري للكاتب أحمد خالد توفيق
رواية الوطواط للكاتب أحمد خالد توفيق
كتاب البكاري والكاهن
كتاب المخالفة الثلاثية في المملكة الحيوانية
كتاب الروحانيات لأمين الريحاني
كتاب أنتم الشعراء
كتاب سجل التوبة
كتاب مص

إمكانية رمضان 2021 فرنسا-تولوز
إمكانية رمضان 2021 فرنسا-باريس
إمكانية رمضان 2021 فرنسا-ليون
إمكانية رمضان 2021 ماليزيا-لنكاوي
إمكانية رمضان 2021 ماليزيا-كوالالمبور
إمكانية رمضان 2021 ماليزيا-سيلانجور
إمكانية رمضان 2021 ماليزيا-بينانج
كتاب تسهيل الفرائض
إمكانية رمضان 2021 أوكرانيا-دونيتسك
انسانية رمضان 2021 رمضان في الهند مدينة كوتشي [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة كيرلا [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة مومباي [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة نيودلهي [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة بونا [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة بوجدور [امساكية رمضان 2021]
إمكانية رمضان 2021 أوكرانيا-لوغانسك
إمكانية رمضان 2021 أوكرانيا-اوديسا
إمكانية رمضان 2021 أوكرانيا-خاركوف
إمكانية رمضان 2021 الصين-نانجينغ
إمكانية رمضان 2021 الصين-شنزن
إمكانية رمضان 2021 الصين-ايوو
إمكانية رمضان 2021 الصين-بكين
كتاب جهنم الصغرى لمصطفى محمود
إمكانية رمضان 2021 الصين-شنغهاي
إمكانية رمضان 2

إمكانية رمضان في اليمن لعام 1442 في 2021
إمكانية رمضان في كندا في هاملتون لعام 1442 في 2021
إمكانية رمضان في كندا في أوتاوا لعام 1442 في 2021
إمكانية رمضان في كندا في فانكوفر لعام 1442 في 2021
إمكانية رمضان في كندا في الجاري لعام 1442 في 2021
إمكانية رمضان في كندا في مونتريال لعام 1442 في 2021
إمكانية رمضان في كندا في فكتوريا لعام 1442 في 2021
إمكانية رمضان في كندا في تورنتو لعام 1442 في 2021
كتاب النور والفراشة
كتاب بلاد الله خلق الله
كتاب ديانات أخرى
انسانية رمضان في السعودية مدينة الطائف لعام 1442 في 2021
انسانية رمضان تركيا مدينة انقرة 2021 لعام 1442 في
انسانية رمضان تركيا مدينة طرابزون 2021 لعام 1442 في
انسانية رمضان تركيا مدينة اسطنبول 2021 لعام 1442 في
انسانية رمضان تركيا مدينة غازي عنتاب 2021 لعام 1442 في
انسانية رمضان تركيا مدينة انطاليا 2021 لعام 1442 في
انسانية رمضان تركيا مدينة المير 2021 لعام 1442 في
انسانية رمضان تركيا مدينة مرسين 2021 لعام 1442 في
انسانية رمضان تركيا مدينة بولو 2021 لعام 1442 في
انسانية رمضان تركيا مدينة ابن 2021 لعام 1442 في
انسانية رمضان تركيا مدينة بو

كتاب المعقول والمعقول في تراثنا الفكري
كتاب الشرق الفنان
كتاب ايام في امريكا
كتاب أسس التفكير العلمي
كتاب الكوميديا الأرضية
كتاب الثلاثية لنجيب محفوظ
كتاب أسطورة الأساطير في
كتاب أسطورة الأساطير في
كتاب أسطورة حامل الضياء في
كتاب أسطورة حامل الضياء في
كتاب أسطورة الفتاة الزرقاء
كتاب أسطورة معرض الرعب
كتاب أسطورة الطفيل
كتاب أسطورة أغنية الموت
كتاب أسطورة شبه مخيفة
كتاب أسطورة الطمطم
سورة الأنعام خط واضح في وتفسيرها
كتاب الله والنفس البشرية pdf
سورة المائدة خط واضح في وتفسيرها
رواية زوجة احمد
رواية كانت صعبة ومغرورة
سورة النساء خط واضح في وتفسيرها
كتاب وطني مصر
رواية ألف ليلة وليلة
رواية شهر العسل
رواية المسرحيات لنجيب محفوظ
رواية القرارا الاخير
رواية يا ابنتى لا تشعرينى معك
رواية همس النجوم
كتاب نموذج الشخصية الدينية في روايات نجيب محفوظ
سورة ال عمران خط واضح في وتفسيرها
كتاب HTML5 and CSS3
رواية السعادة ليس لها تاريخ
رواية الحب في رحاب الله
كتاب HTML and CSS 1st Edition
كتاب تعلم HTML5 في سطور
رواية النظارة السوداء
رواية وعاشت بين أصابعه
رواية حتى لا يطير الدخان
رواية على لوز لنجيب مح

كتاب توريلو وكريسيما
كتاب هنري الخامس
كتاب ثنائية هنري الرابع
كتاب هنري السادس ج1&ج2
كتاب مأساة كريملان
كتاب كلوديوس شكسبير
كتاب جعجعة بدون طحن
كتاب المسيخ الدجال
رواية الرابح يبقى وحيدا
رواية إحدى عشر دقيقة
رواية دليل فارس النور
كتاب محمد صلى الله عليه وسلم
كتاب الجاسوسة للكاتب باولو كويلو
كتاب مكتوب للكاتب باولو كويلو
كتاب السيميائي ساحر الصحراء
كتاب كالنهر الذى يجري
كتاب أوراق محارب الضوء
كتاب مخطوطة وجدت في عكرا
كتاب رجل تحت الصفر
كتاب فتيات فاليري
كتاب الشيخ الهندي
كتاب الشمعدان الحديدي
كتاب السندباد البحري
كتاب السنجاب الصغير
كتاب السعيد حسن
كتاب الديك الظريف
كتاب الدجاجة الصغيرة الحمراء
كتاب الحمار القارئ
كتاب التاجر مرمر
كتاب البيت الجديد
كتاب الأميرة القاسية
كتاب الأمير مشمش
كتاب مصطلح الحديث
كتاب القواعد المثلى في صفات الله وأسمائه الحسنى
كتاب قواعد في الإملاء
كتاب أناشيد الإثم والبراءة
كتاب شرح العقيدة الواسطية
كتاب اهدنا الداء والدواء
كتاب تساؤلات قلوب حائرة
كتاب رحلة المشتاق للحج والعمرة
كتاب من الطارق أنا رمضان
كتاب المهاجرون الجدد
كتاب هبي تاريخ الإيمان
كتاب نقطة رجوع
كت

كتاب إدارة عصر البطالة
كتاب إعلان عن جريمة
كتاب ساحر النساء
كتاب المرأة في عصر الديمقراطية
كتاب مملكة جهنم والخمر
كتاب حِكَم النبي مُحمَّد
كتاب اعترافات تولستوي
كتاب قضية ستايلز الغامضة
كتاب إنجيل تولستوي وديانته
كتاب يوليوس قيصر
كتاب الجريمة النائمة
كتاب ليل لا ينتهى
كتاب جثة فى المكتبة
كتاب الأسد الطائر
كتاب هملت للكاتب ويليام شكسبير
كتاب أكبر للكاتب ويليام شكسبير
كتاب عطيل للكاتب ويليام شكسبير
كتاب البيت المائل
كتاب ضجة فارغة
كتاب ترويض النمرة
كتاب تاجر البندقية
كتاب ذكريات أجاثا كريستي
كتاب الملك لير
كتاب العبرة بالخواتيم
كتاب مناجاة أرواح
كتاب رجل بلا وجه
كتاب رمل وزبد
كتاب دمعة وابتسامة
كتاب العواصف للكاتب جبران خليل جبران
كتاب البدائع والطرائف
كتاب الضحية العاشرة
كتاب الأرواح المتمردة
كتاب الأجنحة المتكسرة
كتاب آلهة الأرض
كتاب الأربعة الكبار
كتاب كليوباترا ملكة مصر
كتاب مصر والحضارة الإسلامية
كتاب الإسلام في الحبشة
كتاب دليل قراءة الى تاريخ الكنيسة
كتاب هيرودوت لا جينيفر تي روبرتس
كتاب الجريمة المعقدة
كتاب الأرنب والصياد
كتاب الأرنب العاصي
كتاب الأرنب الذكي
كتاب ابن جبير في مصر 

رواية حرب الاندال
رواية عندما يصبح الانتقام عدالة الجزء الثالث
قصة الخطر
قصة مغامرة كوبر بيتميز
قصة مغامرة روسكوم أولد بليس
قصة مغامرة النبيل الأعزب
قصة لغز وادي بوسكورة
قصة مغامرة إبهام المهندس
كتاب قوة التركيز وتحسين الذاكرة
قصة مغامرة العميل المرموق
قصة مغامرة الجوهرة الزرقاء
قصة بذور البرتقال الخمس
كتاب اكستازي أن يوم
كتاب فلسطين التاريخ المصور
كتاب الأوبئة والتاريخ المرض والقوة والإمبريالية
كتاب فلسفة التاريخ
كتاب عظماء ومشاهير معاقون غيروا مجرى التاريخ
كتاب من خطأ وأسلوبا مرفوضا في تربية الأطفال
كتاب فن إدارة المواقف الجزء الأول
كتاب أينشتين والنسبية
كتاب كيف تكون كاتباً بارعاً
كتاب من شارع النجاح
قصة المغامرة الأخيرة
قصة مغامرة تشارلز أوجست ميلفيرتون
قصة مغامرة الرجال الراقصين
قصة مغامرة العصابة الرقباء
كتاب تاريخ مصر والسودان الحديث والمعاصر
كتاب الإسلام والعربية في السودان
كتاب السودان في البرلمان المصري
كتاب جماعات غرب افريقيا
كتاب حياة الشرق دوله وشعوبه وماضيه وحاضره
كتاب مصر والسودان كفاح مشترك
كتاب وادي النيل مصر والسودان
كتاب مياه النيل الوعد والوعيد
كتاب السودان دراسة جغ

انسانية رمضان 2020 لعام 1441 في [امساكية رمضان 2020]
كتاب ابدأ بالأهم ولو كان صعبا
كتاب محمد نبي لزماننا
كتاب للرجال فقط
كتاب اول ما ساعة للكاتب جوش كوفمان
تحميل سورة الكهف خط كبير واضح
قصة ورواية بلد العميان pdf احمد خالد توفيق
كتاب أيقظ قواك الخفية أنتوني روبنز
كتاب قوة العادات تشارلز دوي
كتاب قوة التفكير وأثاره على حياتك ابراهيم الفقى
كتاب كيف تكسب الأصدقاء وتؤثر في الناس
كتاب لغات الحب الخمس جاري شابمان
القرآن الكريم باللغة الصينية 古蘭經》中文
كتاب من الذي حرك قطعة الجبن الخاصة بي
كتاب قوة التحكم بالذات ابراهيم الفقي
كتاب إدارة الوقت ابراهيم الفقي
كتاب قوة عقلك الباطن جوزيف ميرفي
كتاب الأب الغني والأب الفقير
القرآن الكريم باللغة التركية Kur’an-ı Kerim Türkçe
القرآن الكريم باللغة الهندية पवित्र कुरान हिंदी में
كتاب القرآن الكريم باللغة الفارسية كتاب قرآن درهم با ترجمه فارسي
القرآن الكريم باللغة الرومانية Sfântul Coran في limba română
القرآن الكريم باللغة الإيطالية أن Sacro Corano في lingua italiana
كتاب جدد حياتك الشيخ محمد الغزالي
كتاب أحترف فن الفراسة ابراهيم الفقي
كتاب أسرار عقل الملي

In [26]:
# Normalization For Text
for i in range(len(df['Title'])):
    sent_norm = normalize_alef_ar(df['Title'][i])
    sent_norm = normalize_alef_maksura_ar(sent_norm)
    sent_norm = normalize_teh_marbuta_ar(sent_norm)
    print(sent_norm)
for i in range(len(df['Category'])):
    sent_norm = normalize_alef_ar(df['Category'][i])
    sent_norm = normalize_alef_maksura_ar(sent_norm)
    sent_norm = normalize_teh_marbuta_ar(sent_norm)
    print(sent_norm)
df.head()

كتاب هدم نظريه التطور في عشرين سؤالا 
كتاب فن التامل 
كتاب الامم البائده 
كتاب المعجزات القرانيه 
كتاب خديعه التطور 
كتاب نداء الفطره لدي الرجل والمراه 
كتاب مع المصطفي 
كتاب بناتي 
كتاب مع الله 
كتاب شكرا ايها الاعداء 
كتاب هموم فتاه ملتزمه 
كتاب طفوله قلب 
كتاب اسئله العنف 
كتاب انا واخواتها 
كتاب من وسائل دفع الغربه 
كتاب مع الائمه 
كتاب زنزانه  لسلمان العوده
كتاب لو كنت طيرا 
كتاب كيف نختلف 
كتاب اسئله الثوره 
كتاب بين الصوره والحقيقه 
كتاب الي قمه القياده العالميه 
كتاب مذكرات الدعوه والداعيه 
كتاب رده ولا ابا بكر لها 
كتاب الاسلام والحكم 
كتاب مله ابراهيم وحضاره الاسلام 
كتاب ترشيد الصحوه الاسلاميه 
كتاب المسلمون تجاه الحضاره الغربيه 
كتاب مقالات حول السيره النبويه 
كتاب الامام الذي لم يوف حقه 
كتاب شخصيات وكتب 
كتاب من اعلام المسلمين ومشاهيرهم 
كتاب رجال الفكر والدعوه ج 3-4 
كتاب رجال الفكر والدعوه ج 1-2 
كتاب الحضاره الغربيه 
كتاب نصائح وتوجيهات 
كتاب عن وطن لحم ودم  للكاتب ادهم الشرقاوي
كتاب خربشات خارجه عن القانون  للكاتب ادهم الشرقاوي
كتاب حديث الصباح  للكاتب ادهم الشرقاوي
ك

كتاب المانيا النازيه 
روايه السيد زخاريوس 
كتاب مفهوم المنهج العلمي 
كتاب فلسفه كارل بوبر 
كتاب مشكله العلوم الانسانيه 
كتاب فلسفه العلم في القرن العشرين 
كتاب ركائز في فلسفه السياسه 
كتاب بحوث في تاريخ العلوم عند العرب 
كتاب الوجوديه الدينيه 
كتاب الطبيعيات في علم الكلام 
كتاب الزمان في الفلسفه والعلم 
كتاب النسويه وفلسفه العلم 
كتاب امين الخولي والابعاد الفلسفيه للتجديد 
كتاب افتراءات شيعيه علي البخاري ومسلم 
كتاب التفسير الماركسي للاسلام 
كتاب المعتزله ومشكله الحريه الانسانيه 
كتاب نهضتنا الحديثه بين العلمانيه والاسلام 
روايه لغز رامي القنبله 
روايه لغز الماسات الخمسمائه 
كتاب الاسلام والمراه 
روايه لغز الثروه المفقوده 
روايه عصابه شاردي الذهن 
روايه دليل الملاعق الفضيه 
كتاب كيس نايلون 
كتاب مثل الساعه المضبوطه 
مجله بطوط وبحيره الكريستال 
مجله بطوط وميكي اللاعب المثالي 
كتاب ابن قيم الجوزيه حياته اثاره موارده 
كتاب الميسر في حياه الخلفاء الراشدين 
روايه تدخل‎ امراه 
روايه الصحفيه جيني باكستر 
كتاب ميكروميغاس وثلاث قصص 
كتاب مريض الوهم 
كتاب جوسلين  لالياس ابو شبكه
كتاب الطرق الحكم

كتاب عثمان بن عفان 
روايه زينب للكاتب محمد حسين هيكل 
كتاب حياه محمد 
كتاب تراجم مصريه وغربيه 
كتاب الفاروق عمر 
كتاب الايمان والمعرفه والفلسفه 
كتاب الامبراطوريه الاسلاميه 
كتاب الامر بالاتباع والنهي عن 
كتاب الموجب لظل العرش 
كتاب اسماء المدلسين 
كتاب مفحمات الاقران في مبهمات القران 
كتاب البحر الذي زخر 
كتاب ضعيف سنن النسائي  للالباني
كتاب صحيح سنن النسائي ج3  للالباني
كتاب صحيح سنن النسائي ج2
كتاب صحيح سنن النسائي ج1
كتاب ما رواه الاساطين في عدم المجيء 
كتاب تحفه المهتدين باخبار المجددين 
كتاب اللمع في اسباب ورود الحديث 
كتاب ضعيف سنن الترمذي  للالباني
كتاب صحيح سنن الترمذي ج3  للالباني
كتاب صحيح سنن الترمذي ج2  للالباني
كتاب صحيح سنن الترمذي ج1
كتاب العشاق الثلاثه 
كتاب التصوف الاسلامي في الادب والاخلاق 
كتاب البدائع  لزكي مبارك
كتاب الاسمار والاحاديث 
كتاب الاخلاق عند الغزالي 
كتاب علي امام المتقين الجزء الثاني 
كتاب علي امام المتقين الجزء الاول 
كتاب عرابي زعيم الفلاحين 
كتاب قصه المسيح الدجال  للالباني
كتاب فتنه التكفير  للالباني
كتاب حكم تارك الصلاه  للالباني
كتاب اصل صفه صلاه

كتاب 53 وسيله للعتق من النيران في رمضان 
كتاب همام في بلاد الاحقاف 
كتاب فن المسرحيه من خلال تجاربي الشخصيه 
كتاب علي اسوار دمشق 
كتاب الوطن الاكبر 
كتاب الشيماء شاديه الاسلام 
كتاب فقه وفتاوي واحكام القيام والتراويح والتهجد والوتر
كتاب 25 فضيله من فضائل العمره 
كتاب كيف تكون من القانتين والمقنطرين في رمضان؟ 
كتاب الايجاز بذكر فتاوي العيدين للعلامه ابن باز 
كتاب اقوال وقصص السلف في الصيام
كتاب اَذْكَارٌ حِسَانٌ يُبْنَي لَكَ بِهَا بُيُوتٌ فِي الجِنَان 
كتاب الكنوز العشر في رمضان
كتاب فقه الاعتكاف واحكامه وفتاويه 
كتاب 20 فضيله لمن فطر صائما 
كتاب فقه زكاه الفطر واحكامها 
كتاب 100 وسيله معينه علي صلاه القيام 
15 فضيله من فضائل ليله القدر 
كتاب فتاوي واختيارات الصيام للعلامه ابن عثيمين
كتاب فتاوي العلماء الاعلام في صلاه التراويح والقيام 
كتاب مشاريع المليارات في رمضان 
كتاب فقه واحكام ليله القدر 
كتاب فقه صلاه الجماعه واحكامها وفتاويها 
كتاب اعمال تعدل عتق الرقاب 
كتاب 44 وسيله للنجاه من عذاب القبر 
كتاب 23 وسيله لتنال الهدايه من الله تعالي 
كتاب اقوال وقصص السلف مع القران وقراءته وتدبره


روايه شيطان الاجيال 
روايه اسري الزمن 
روايه سجن القمر 
روايه المحيط الملتهب 
روايه قضيه قتيل الفندق 
روايه الحرباء 
روايه النهر الاسود 
روايه المخاطر 
روايه مضيق النيران 
روايه ابواب الجحيم 
روايه عقول الشر 
روايه ثقب في التاريخ 
روايه بلا رؤوس 
كتاب انت جيش عدوك 
روايه لغز المتحف الحديث 
روايه الزئبق الجاف 
روايه الرمال الحيه 
روايه الاعماق 
كتاب العاصفه 
كتاب الفارس الثاني 
كتاب مجموع الفتاوي جزء 25 
كتاب مجموع الفتاوي جزء 24 
كتاب مجموع الفتاوي جزء 23 
كتاب مجموع الفتاوي جزء 22 
كتاب مجموع الفتاوي جزء 21 
كتاب التحذير من العرف الخاطئ والخداع اللفظي للشيخ يوسف القرضاوي 
كتاب الامام الغزالي بين مادحيه وناقديه للشيخ يوسف القرضاوي 
كتاب القواعد الحاكمه في فقه المعاملات للشيخ يوسف القرضاوي 
كتاب الشيخ الغزالي كما عرفته للشيخ يوسف القرضاوي 
كتاب السياسه الشرعيه للشيخ يوسف القرضاوي 
كتاب الاسلام الذي ندعوا اليه للشيخ يوسف القرضاوي 
كتاب خطب الشيخ القرضاوي ج1 للشيخ يوسف القرضاوي 
كتاب الورع والزهد للشيخ يوسف القرضاوي 
كتاب واجبنا نحو القران الكريم للشيخ يوسف القرضاوي 
كتاب الصحوه الاسلاميه

كتاب اليتيم للسحار 
كتاب مولد الرسول 
كتاب الديباج علي صحيح مسلم 
كتاب شرح عقود الجمان 
كتاب المسارعه الي المصارعه 
كتاب الاكليل في استنباط التنزيل 
كتاب تحفه الطالب بمعرفه احاديث مختصر ابن الحاجب  للحافظ ابن كثير
كتاب اختصار علوم الحديث  للحافظ ابن كثير
كتاب السيره النبويه  للحافظ ابن كثير مقدمه الكتاب
كتاب السيره النبويه ج4  للحافظ ابن كثير
كتاب السيره النبويه ج3  للحافظ ابن كثير
كتاب قريش للسحار 
كتاب العدنانيون للسحار 
كتاب بنو اسماعيل 
كتاب هاجر المصريه ام العرب 
كتاب ابراهيم ابو الانبياء 
كتاب قصص الخلفاء الراشدين 
كتاب قصص السيره 
كتاب العرب في اوروبا 
كتاب قدر الله 
كتاب قصص الانبياء اهل الكهف 
كتاب السيره النبويه ج2 لابن كثير 
كتاب السيره النبويه ج1  للحافظ ابن كثير
كتاب تفسير ابن كثير  للحافظ ابن كثير القران كاملًا
كتاب تمهيد الفرش في الخصال الموجبه لظل العرش 
كتاب لباب النقول في اسباب النزول 
كتاب سهام الاصابه في الدعوات المجابه 
كتاب ارشاد الفقيه الي ادله التنبيه ج2 
كتاب ارشاد الفقيه الي ادله التنبيه 
روايه المفقودون 
روايه انياب 
روايه المخ 
روايه الثعابين 
كتاب اطلال الم

تفسير سوره المائده لابن كثير 
تفسير سوره النساء لابن كثير 
كتاب مفسدات القلوب العشق 
كتاب اعمال القلوب الورع 
كتاب مفسدات القلوب الترف 
كتاب مفسدات القلوب الشهوه 
كتاب اعمال القلوب الخوف 
كتاب اعمال القلوب التوكل 
كتاب مفسدات القلوب الغفله 
كتاب محرمات استهان بها كثير من الناس 
كتاب السفر اداب واحكام 
كتاب 33 سبباً للخشوع في الصلاه 
كتاب اخطار تهدد البيوت 
كتاب رمضان فرصه للتربيه والتعليم 
كتاب زاد الحج 
كتاب 70 مساله في الصيام 
كتاب مفسدات القلوب 
كتاب اعمال القلوب الشكر 
كتاب كيف تقرا كتاباَ 
كتاب الجدال والمراء 
كتاب اربعون نصيحه لاصلاح البيوت
كتاب اعمال القلوب 
تفسير سوره التوبه لابن كثير 
تفسير سوره البقره لابن كثير 
كتاب في صفه صاحب الذوق السليم 
روايه سبعه مفاتيح لبالدبيت 
روايه احزان الشيطان 
روايه تايبي للكاتب احمد خالد توفيق 
روايه ساحر اوز 
روايه الافق المفقود 
روايه التنين الاحمر 
روايه افضل قصص الاشباح 
روايه الرجل الخفي 
تفسير سوره البقره لابن كثير 
تفسير سوره الفاتحه لابن كثير 
تفسير سوره البقره لابن كثير 
كتاب تفسير سوره الفاتحه 
روايه المهمه الانتحاريه pdf
روايه رجل بس

كتاب تاريخ الحروب الصليبيه ج 36 
كتاب تاريخ الحروب الصليبيه ج 35 
كتاب تاريخ الحروب الصليبيه ج 34 
كتاب تاريخ الحروب الصليبيه ج 32 
كتاب تاريخ الحروب الصليبيه ج 31 
كتاب تاريخ الحروب الصليبيه ج 30 
كتاب تاريخ الحروب الصليبيه ج 29 
كتاب تاريخ الحروب الصليبيه ج 28 
كتاب تاريخ الحروب الصليبيه ج 26 
كتاب تاريخ الحروب الصليبيه ج 25 
كتاب تاريخ الحروب الصليبيه ج 24 
كتاب تاريخ الحروب الصليبيه ج 23 
كتاب تاريخ الحروب الصليبيه ج 22 
كتاب تاريخ الحروب الصليبيه ج 21 
كتاب تاريخ الحروب الصليبيه ج 20 
كتاب تاريخ الحروب الصليبيه ج 19 
كتاب تاريخ الحروب الصليبيه ج 18 
كتاب تاريخ الحروب الصليبيه ج 17 
كتاب تاريخ الحروب الصليبيه ج 16 
كتاب تاريخ الحروب الصليبيه ج 15 
كتاب تاريخ الحروب الصليبيه ج 14 
كتاب تاريخ الحروب الصليبيه ج 13 
كتاب تاريخ الحروب الصليبيه ج 12 
كتاب تاريخ الحروب الصليبيه ج 11 
كتاب تاريخ الحروب الصليبيه ج 10 
كتاب تاريخ الحروب الصليبيه ج 9 
كتاب تاريخ الحروب الصليبيه ج 8 
كتاب تاريخ الحروب الصليبيه ج 7 
كتاب تاريخ الحروب الصليبيه ج 6 
كتاب تاريخ الحروب الصليبيه ج 5 
كتاب تاريخ الحر

امساكيه رمضان في امريكا ولايه بوسطن 2021 
كتاب تفسير احلام التشاؤم  لابن سيرين
كتاب معني الكلام 
روايه يونس في بطن الحوت 
روايه هو الذي طغي 
روايه من قتل الطفل 
روايه داء الاسد 
روايه الي الشمال 
كتاب تعطير الانام في تعبير المنام لابن سيرين 
روايه هم للكاتب احمد خالد توفيق 
روايه سيد الجينات 
كتاب تفسير احلام التفاؤل لابن سيرين 
كتاب تفسير الاحلام الكبير لابن سيرين 
كتاب منتخب الكلام في تفسير الاحلام 
معجم تفسير الاحلام لابن سيرين والنابلسي 
كتاب مدرسه الحكمه 
كتاب لم الفلسفه 
كتاب دموع البلياتشو 
روايه القلب ابدا يدق 
روايه الا فاطمه 
كتاب شباب شباب 
كتاب مذكرات شابه غاضبه 
كتاب قالوا لانيس منصور 
كتاب الخروج من التابوت 
كتاب نهايه العالم 
كتاب جسمك لا يكذب 
كتاب الافيون  لمصطفي محمود
كتاب رائحه الدم  لمصطفي محمود
كتاب اسرائيل النازيه ولغه المحرقه 
كتاب ايها الساده اخلعوا الاقنعه 
كتاب السحر والحسد 
كتاب الهجره النبويه 
كتاب ايزيس 
كتاب الورطه لتوفيق الحكيم 
كتاب الملك اوديب 
كتاب يقظه الفكر 
كتاب نشيد الانشاد 
كتاب مصير صرصار 
كتاب مسرحيه الحمير 
كتاب لو عرف الشباب 
كتاب دعوه للفلسفه

كتاب هنري الخامس 
كتاب ثنائيه هنري الرابع 
كتاب هنري السادس ج1&ج2 
كتاب ماساه كريولانس 
كتاب كلوديوس  لشيكسبير
كتاب جعجعه بدون طحن 
كتاب المسيخ الدجال 
روايه الرابح يبقي وحيدا 
روايه احدي عشر دقيقه 
روايه دليل فارس النور 
كتاب محمد صلي الله عليه وسلم 
كتاب الجاسوسه  للكاتب باولو كويلو
كتاب مكتوب  للكاتب باولو كويلو
كتاب السيميائي ساحر الصحراء 
كتاب كالنهر الذي يجري 
كتاب اوراق محارب الضوء 
كتاب مخطوطه وجدت في عكرا 
كتاب رجل تحت الصفر 
كتاب فتيات فالكيري 
كتاب الشيخ الهندي 
كتاب الشمعدان الحديدي 
كتاب السندباد البحري 
كتاب السنجاب الصغير 
كتاب السعيد حسن 
كتاب الديك الظريف 
كتاب الدجاجه الصغيره الحمراء 
كتاب الحمار القارئ 
كتاب التاجر مرمر 
كتاب البيت الجديد 
كتاب الاميره القاسيه 
كتاب الامير مشمش 
كتاب مصطلح الحديث 
كتاب القواعد المثلي في صفات الله واسمائه الحسني 
كتاب قواعد في الاملاء 
كتاب اناشيد الاثم والبراءه 
كتاب شرح العقيده الواسطيه 
كتاب اهدنا الداء والدواء 
كتاب تساؤلات قلوب حائره 
كتاب رحله المشتاق للحج والعمره 
كتاب من الطارق انا رمضان 
كتاب المهاجرون الجدد 
كتاب هبي ياريح ا

كتاب مصر والسودان كفاح مشترك 
كتاب وادي النيل مصر والسودان 
كتاب مياه النيل الوعد والوعيد 
كتاب السودان دراسه جغرافيه 
كتاب السودان الي اين بالعربيه 
كتاب السودان الي اين الاصلي 
كتاب تاريخيه الفكر العربي الاسلامي 
كتاب رحله الي مصر والسودان والحبش 
كتاب السيف والنار في السودان 
كتاب اصنع لنفسك ماركه 
كتاب 15 فضيله من فضائل ليله القدر 
قصه مغامره منزل ابي جرينج 
قصه مغامره المنزل ذي الاسقفِ المُحدَّبه الثلاثه 
قصه مغامره جوهره مازارين 
قصه مغامره الجندي الشاحب 
كتاب ليله القدر 
كتاب المرشد الكامل للمشروعات الصغيره 
كتاب كيف تقرا افكار الاخرين من خلال حركاتهم 
كتاب القياده مقدمه قصيره جدا 
قصه مغامره المنزل الخالي 
قصه مغامره بيتر الاسود 
قصه مغامره راكبه الدراجه في الطريق المهجور 
قصه مغامره المحقق المحتضر 
روايه مدرسه محمد صلي الله عليه وسلم  
روايه لغز بربروسا 101 
كتاب الهجره حدث غير مجري التاريخ 
كتاب كل رجال الباشا محمد علي 
روايه 101 سر اريوس  
كتاب الفتح والاستقرار العربي الاسلامي في شمال افريقيا والاندلس 
كتاب مصطلح التاريخ 
كتاب العلاقات السياسيه بين الدول الامويه في الاندلس 


كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
العلوم السياسيه والاستراتيجيه
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
كتب اسلاميه
كتب الادب العربي
كتب الادب العربي
كتب الادب العربي
كتب الادب العربي
العلوم السياسيه والاستراتيجيه
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب اسلاميه
اعلام وشخصيات
كتب اسلاميه
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
اللغه 

العقيده
الادب
العقيده
كتب علم النفس
الادب
الادب
كتب علم النفس
كتب علم النفس
كتب الاطفال
كتب الاطفال
كتب علم النفس
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الاطفال
كتب علم النفس
كتب علم النفس
كتب الاطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الاطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب علم النفس
كتب الاطفال
كتب الاطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الاطفال
كتب الاطفال
الادب
كتب الاطفال
الادب
كتب الاطفال
الادب
الادب
كتب الاطفال
الادب
الادب
كتب الاطفال
الادب
كتب الاطفال
الادب
كتب الاطفال
الادب
الادب
كتب الاطفال
الادب
الادب
الادب
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الاطفال
كتب الادب العربي
كتب الاطفال
كتب اسلاميه
كتب الاطفال
كتب الاطفال
العقيده
كتب الاطفال
العقيده
كتب الاطفال
العقيده
العقيده
كتب الاطفال
العقيده
كتب الاطفال
كتب اسلاميه
ك

روايات بوليسيه
روايات بوليسيه
العقيده
روايات بوليسيه
العقيده
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
العقيده
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
العقيده
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
العلوم السياسيه والاستراتيجيه
العلوم السياسيه والاستراتيجيه
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
العقيده
روايات 

كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
القران الكريم
القران الكريم
القران الكريم
القران الكريم
القران الكريم
القران الكريم
القران الكريم
تفاسير
القران الكريم
القران الكريم
تفاسير
القران الكريم
القران الكريم
القران الكريم
تفاسير
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
القران الكريم
تفاسير
القران الكريم
القران الكريم
القران الكريم
تفاسير
تفاسير
تفاسير
القران الكريم
القران الكريم
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
القران الكريم
كتب اسلاميه
القران الكريم
القران الكريم
القران الكريم
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسل

كتب الروايات العالميه المترجمه
كتب الروايات العالميه المترجمه
كتب الروايات العالميه المترجمه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
كتب روايات عربيه
الادب
كتب التاريخ
الادب
الثقافه العامه
كتب اسلاميه
كتب التاريخ الاسلامي
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتاب:
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كتب التاريخ
كت

كتب التاريخ الحديث
كتب اسلاميه
كتب الادب العربي
كتب تطوير الذات
كتب التنميه الذاتيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
كتب التاريخ القديم
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
كتب اسلاميه
كتب اسلاميه
كتب القصص القصيره
كتب اسلاميه
كتب اسلاميه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
كتب علم الاجتماع
كتب اساطير
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب اسلاميه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
القران الكريم
كتب اسلاميه
كتب التنميه الذاتيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
روايات بوليسيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب التنميه الذاتيه
كتب الت

كتب التاريخ القديم
كتب اسلاميه
كتب الادب العربي
كتب التاريخ الحديث
كتب اسلاميه
كتب اسلاميه
كتب التاريخ الحديث
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
كتب اسلاميه
كتب اسلاميه
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
كتب اسلاميه
كتب اسلاميه
كتب الادب العربي
كتب التاريخ الحديث
كتب التاريخ الاسلامي
كتب الادب العربي
كتب الادب العربي
كتب التاريخ الاسلامي
كتب الادب العربي
كتب اسلاميه
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
القران الكريم
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
كتب التاريخ الحديث
كتب التاريخ
كتب التاريخ
كتب التاريخ الاسلامي
كتب روايات عربيه
كتب اسلاميه
كتب الادب العربي
كتب التاريخ
كتب السيره النبويه
كتب التاريخ الاسلامي
كتب مقارنه الاديان
كتب التاريخ
كتب التاريخ القديم
كتب التاريخ القديم
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب التاريخ الاسلامي
كتب التاريخ الاسلامي
كتب التاريخ
كتب الادب العربي
كتب التاريخ الحديث
كتب التاريخ الاسلامي
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب التاريخ القديم
كتب التاريخ القديم
كت

Author                                  Title  \
0  الكاتب هارون يحيىالكاتب هارون يحيى  كتاب هدم نظرية التطور في عشرين سؤالا    
1  الكاتب هارون يحيىالكاتب هارون يحيى                        كتاب فن التأمل    
2  الكاتب هارون يحيىالكاتب هارون يحيى                    كتاب الأمم البائدة    
3  الكاتب هارون يحيىالكاتب هارون يحيى                كتاب المعجزات القرآنية    
4  الكاتب هارون يحيىالكاتب هارون يحيى                     كتاب خديعة التطور    

                                        Link for PDF             Category  \
0  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
1  https://www.arab-books.com/books/%d9%83%d8%aa%...     كتب الأدب العربي   
2  https://www.arab-books.com/books/%d9%83%d8%aa%...       الثقافة العامة   
3  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
4  https://www.arab-books.com/books/%d9%83%d8%aa%...  كتب الفلسفة والمنطق   

   Number Of Pages  
0              154  
1               68  
2              162  
3               99  
4              258

In [27]:
# Check For Null Values
df.isnull()

Author  Title  Link for PDF  Category  Number Of Pages
0      False  False         False     False            False
1      False  False         False     False            False
2      False  False         False     False            False
3      False  False         False     False            False
4      False  False         False     False            False
...      ...    ...           ...       ...              ...
5935   False  False         False     False            False
5936   False  False         False     False            False
5937   False  False         False     False            False
5938   False  False         False     False            False
5939   False  False         False     False            False

[5940 rows x 5 columns]

In [28]:
df.isnull().sum()

Author             251
Title                0
Link for PDF         0
Category             0
Number Of Pages      0
dtype: int64

In [29]:
df.describe()

Number Of Pages
count      5940.000000
mean        183.487542
std         185.662309
min           1.000000
25%          52.000000
50%         126.000000
75%         242.000000
max         992.000000

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5940 entries, 0 to 5939
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Author           5689 non-null   object
 1   Title            5940 non-null   object
 2   Link for PDF     5940 non-null   object
 3   Category         5940 non-null   object
 4   Number Of Pages  5940 non-null   int64 
dtypes: int64(1), object(4)
memory usage: 232.2+ KB


In [31]:
pd.crosstab(df['Author'], df['Title'], margins=True)

Title                                               15 فضيلة من فضائل ليلة القدر   \
Author                                                                              
Andy Harris                                                                     0   
David Graeber                                                                   0   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...                              0   
David H. Weiss                                                                  0   
Steven Pinker                                                                   0   
...                                                                           ...   
يوسف إدريس                                                                      0   
يوسف العش                                                                       0   
يوسف كرم                                                                        0   
يوسي إم هانيماكي                                                                0   
All                                                                             1   

Title                                               Corán traducido al español  – القران نسخة اسبانية  \
Author                                                                                                  
Andy Harris                                                                                         0   
David Graeber                                                                                       0   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...                                                  0   
David H. Weiss                                                                                      0   
Steven Pinker                                                                                       0   
...                                                                                               ...   
يوسف إدريس                                                                                          0   
يوسف العش                                                                                           0   
يوسف كرم                                                                                            0   
يوسي إم هانيماكي                                                                                    0   
All                                                                                                 1   

Title                                               The book of”Bullshit Jobs”   \
Author                                                                            
Andy Harris                                                                   0   
David Graeber                                                                 1   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...                            0   
David H. Weiss                                                                0   
Steven Pinker                                                                 0   
...                                                                         ...   
يوسف إدريس                                                                    0   
يوسف العش                                                                     0   
يوسف كرم                                                                      0   
يوسي إم هانيماكي                                                              0   
All                                                                           1   

Title                                               bullshit jobs   \
Author                                                               
Andy Harris                                                      0   
David Graeber                                                    1   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...               0   
David H. Weiss                                                   0   
Steven Pinker               

In [34]:
# Clean DataSet And Replace Null Values
df.dropna(inplace=True)
df.isnull().sum()

Author             0
Title              0
Link for PDF       0
Category           0
Number Of Pages    0
dtype: int64

In [35]:
df.describe()

Number Of Pages
count      5689.000000
mean        189.633503
std         186.250057
min           1.000000
25%          56.000000
50%         130.000000
75%         253.000000
max         992.000000

# Split Data To Train and Test Data

In [36]:
from sklearn.model_selection import train_test_split
author = df['Author']
title = df['Title']
X = (author)+(title)
y= df['Category']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
y_train.value_counts(), y_test.value_counts()

(كتب اسلامية         1027
 روايات بوليسية       493
 كتب روايات عربية     456
 كتب الأدب العربي     347
 العقيدة              306
                     ... 
 علوم اللغة             1
 علوم الحاسب            1
 كتب تاريخ اوروبا       1
 الرياضيات              1
 الفن                   1
 Name: Category, Length: 72, dtype: int64,
 كتب اسلامية                          267
 روايات بوليسية                       117
 كتب روايات عربية                     112
 كتب الأدب العربي                      92
 العقيدة                               78
 كتب الأطفال                           51
 كتب الروايات العالمية المترجمة        40
 الأدب                                 33
 الثقافة العامة                        30
 كتب التنمية الذاتية                   27
 القرآن الكريم                         21
 كتب الأدب العالمي المترجم             20
 كتب التاريخ                           20
 كتب علم النفس                         19
 كتب التاريخ الحديث                    19
 كتب القصص القصيرة المترجمة            16

# Importing Models  

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

# Buliding LinearSVC

In [40]:
text_clf_svm = Pipeline([('tfidf',TfidfVectorizer()),
                       ('svc', LinearSVC()),])
text_clf_svm.fit(X_train, y_train)
predictions = text_clf_svm.predict(X_test)

# Measure Accuracy

In [41]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.accuracy_score(y_test, predictions))

[[ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0 17 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  0  0  0]]
0.7521968365553603


# Buliding RandomForest

In [42]:
from sklearn.ensemble import RandomForestClassifier
text_clf_rf = Pipeline([('tfidf',TfidfVectorizer()),
                       ('svc',RandomForestClassifier(n_estimators=1800, random_state=0)),])
text_clf_rf.fit(X_train, y_train)
predictions = text_clf_rf.predict(X_test)

# Measure Accuracy

In [44]:
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.accuracy_score(y_test, predictions))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 16 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  0]]
0.7530755711775043


# Buliding LogisiticRegression

In [45]:
from sklearn.linear_model import LogisticRegression
text_clf_lg = Pipeline([('tfidf',TfidfVectorizer()),
                       ('lg',LogisticRegression(random_state=0)),])
text_clf_lg.fit(X_train, y_train)
predictions = text_clf_lg.predict(X_test)

# Measure Accuracy

In [46]:
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.accuracy_score(y_test, predictions))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
0.7240773286467487


# Bulid KNN 

In [54]:
from sklearn.neighbors import KNeighborsClassifier
text_clf_knn = Pipeline([('tfidf',TfidfVectorizer()),
                       ('knn',KNeighborsClassifier(n_neighbors=3)),])
text_clf_knn.fit(X_train, y_train)
prediction = text_clf_knn.predict(X_test)

# Measure Accuracy

In [55]:
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.accuracy_score(y_test, predictions))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
0.7240773286467487
