In [1]:
#Importing Libiraries
from ar_corrector.corrector import Corrector
import numpy as np
import pandas as pd
from pandas import read_csv

In [2]:
# Read DataSet
url='D:\en.csv'
df = read_csv(url, encoding='utf-8-sig')
df.shape

(5940, 5)

In [3]:
df.head()

Author                                  Title  \
0  الكاتب هارون يحيىالكاتب هارون يحيى  كتاب هدم نظرية التطور في عشرين سؤالا    
1  الكاتب هارون يحيىالكاتب هارون يحيى                        كتاب فن التأمل    
2  الكاتب هارون يحيىالكاتب هارون يحيى                    كتاب الأمم البائدة    
3  الكاتب هارون يحيىالكاتب هارون يحيى                كتاب المعجزات القرآنية    
4  الكاتب هارون يحيىالكاتب هارون يحيى                     كتاب خديعة التطور    

                                        Link for PDF             Category  \
0  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
1  https://www.arab-books.com/books/%d9%83%d8%aa%...     كتب الأدب العربي   
2  https://www.arab-books.com/books/%d9%83%d8%aa%...       الثقافة العامة   
3  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
4  https://www.arab-books.com/books/%d9%83%d8%aa%...  كتب الفلسفة والمنطق   

   Number Of Pages  
0              154  
1               68  
2              162  
3               99  
4              258

In [4]:
# AutoCorrect For DataSet
corr = Corrector()
for i in range(len(df['Category'])):
    print(corr.contextual_correct(df['Category'][i]))
for i in range(len(df['Title'])):
        print(corr.contextual_correct(df['Title'][i]))  

كتب اسلامية
كتب الأدب العربي
الثقافة العامة
كتب اسلامية
كتب الفلسفة والمنطق
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب أدب السجون
كتب الأدب العربي
كتب الأدب العربي
العلوم السياسية والاستراتيجية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
الأدب
الأدب
الأدب
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلام

كتب اسلامية
كتب الأطفال
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
الأدب
العقيدة
علوم القرآن الكريم والسنة النبوية
الأدب
العقيدة
كتب الأدب العربي
الأدب
العقيدة
الأدب
الأدب
العقيدة
العقيدة
الأدب
العقيدة
الأدب
الأدب
الأدب
العقيدة
العقيدة
العقيدة
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب علم النفس
العقيدة
كتب علم النفس
الأدب
العقيدة
كتب علم النفس
كتب علم النفس
كتب علم النفس
الأدب
كتب علم النفس
الأدب
كتب علم النفس
كتب علم النفس
الأدب
الأدب
كتب علم النفس
الأدب
كتب علم النفس
العقيدة
العقيدة
العقيدة
العقيدة
الأدب
العقيدة
كتب علم النفس
الأدب
الأدب
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب الأطفال
كتب علم النفس
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب علم النفس
كتب علم النفس
كتب علم النفس
كتب الأطفال
كتب الأطفال
كتب الأطفال
كتب الأطف

كتاب
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب روايات عربية
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتاب
كتب اسلامية
كتب متنوعة
العقيدة
العقيدة
العقيدة
العلوم السياسية والاستراتيجية
تفاسير
العقيدة
العقيدة
العقيدة
العقيدة
كتب التاريخ
روايات بوليسية
روايات بوليسية
كتب روايات عربية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
كتاب
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اس

كتاب
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
الثقافة العامة
روايات بوليسية
الثقافة العامة
روايات بوليسية
الثقافة العامة
الثقافة العامة
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
علوم القرآن الكريم والسنة النبوية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
روايات بوليسية
ر

كتاب
كتب اسلامية
كتاب
كتب اسلامية
كتب اسلامية
الأدب
كتب اسلامية
كتب اسلامية
كتب اسلامية
الطب
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
كتب اسلامية
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
كتب الأدب العربي
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
القرآن الكريم
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب الأدب العربي
كتب

كتاب
رمضانيات
كتب أصول الفقه
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
الأدب
رمضانيات
رمضانيات
كتب اسلامية
رمضانيات
الثقافة العامة
رمضانيات
رمضانيات
رمضانيات
رمضانيات
العلوم السياسية والاستراتيجية
رمضانيات
كتب روايات عربية
كتب روايات عربية
رمضانيات
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب القصص القصيرة
كتب أصول الفقه
رمضانيات
الأدب
كتب أصول الفقه
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتب أدب الرحلات
الأدب
كتب أدب الرحلات
الثقافة العامة
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتاب
كتب الأدب العربي
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
كتاب
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
رمضانيات
كتب روايات عربية
رمضانيات
رمضانيات
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب روايات عربية
كتب رو

كتب اسلامية
كتب الأدب العربي
كتب التاريخ الحديث
كتب اسلامية
كتب اسلامية
كتب التاريخ الحديث
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
كتب اسلامية
كتب اسلامية
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
كتب اسلامية
كتب اسلامية
كتب الأدب العربي
كتب التاريخ الحديث
كتب التاريخ الإسلامي
كتب الأدب العربي
كتب الأدب العربي
كتب التاريخ الإسلامي
كتب الأدب العربي
كتب اسلامية
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
القرآن الكريم
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
كتب التاريخ الحديث
كتب التاريخ
كتب التاريخ
كتب التاريخ الإسلامي
كتب روايات عربية
كتب اسلامية
كتب الأدب العربي
كتب التاريخ
كتب السيرة النبوية
كتب التاريخ الإسلامي
كتب مقارنة الأديان
كتب التاريخ
كتب التاريخ القديم
كتب التاريخ القديم
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب التاريخ الإسلامي
كتب التاريخ الإسلامي
كتب التاريخ
كتب الأدب العربي
كتب التاريخ الحديث
كتب التاريخ الإسلامي
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب التاريخ الحديث
كتب التاريخ القديم
كتب التاريخ القديم
كتب التاريخ الإسلامي


كتاب من أعلام المسلمين مشاهيرهم
كتاب رجال الفكر والدعوة ج 3-4
كتاب رجال الفكر والدعوة ج 1-2
كتاب الحضارة الغربية
كتاب نصائح وتوجيهات
كتاب عن وطن لحم ودم للكاتب أدهم الشرقاوي
كتاب خربشات خارجة عن القانون للكاتب أدهم الشرقاوي
كتاب حديث الصباح للكاتب أدهم الشرقاوي
كتاب قصص النبيين للأطفال
كتاب الطريق إلى المدينة
كتاب المرتضى
كتاب النبوة والأنبياء
كتاب من الجاهلية إلى الإسلام
كتاب نفحات الإيمان
كتاب مسئولية العلماء في الأوضاع المتغيرة
كتاب موقف العالم الإسلامي
كتاب من نهر كابل إلى نهر اليرموك
كتاب صورتان متضادتان
كتاب الطريق إلى السعادة
كتاب البلاغة تطور وتاريخ
كتاب الحب العذرى عند العرب
كتاب البحث الأدبي
كتاب جواهر القلوب للكاتب أبو حامد الغزالي
كتاب منهاج العابدين إلى الجنة للكاتب أبو حامد الغزالي
كتاب شوقى شاعر العصر الحديث
كتاب تهذيب المهلكات والمنجزات للكاتب أبو حامد الغزالي
كتاب مجربات الغزالي في الطب الروحاني للكاتب أبو حامد الغزالي
كتاب الأطفال للكاتب أبو حامد الغزالي
كتاب خافية الحروف الثمانية والعشرين للكاتب أبو حامد الغزالي
كتاب التفكر في خلق الله للكاتب أبو حامد الغزالي
كتاب ال

كتاب البلدان والعرفان والعصيان والجولان
كتاب فلسفة الجد والهزل
كتاب تهذيب الحيوان للجاحظ
كتاب القول في البغال
كتاب العثمانية للجاحظ
كتاب الحنين إلى الأوطان
كتاب المحاسن والأجداد
كتاب رسائل الجاحظ
كتاب الحيوان المجلد الثالث
كتاب البيان والتبيين المجلد الأول
رواية البخلاء نسخة اخري
كتاب البيان والتبيين المجلد الرابع
كتاب البيان والتبيين المجلد الثالث
كتاب الحيوان المجلد الثاني
كتاب الحيوان المجلد الأول
كتاب الحيوان للجاحظ
رواية البخلاء كتابة جديدة
كتاب البيان والتبيين المجلد الثاني
كتاب مقدمة البيان والتبيين
كتاب إزالة أسباب الخذلان
كتاب ماذا خسر العالم بانحطاط المسلمين
كتاب المصباح الفضي
كتاب لصوص نيويورك
كتاب أرسين لوبين المجرم
كتاب الدائرة السوداء
كتاب أرسين لوبين الشريف pdf
كتاب سر عقد اللؤلؤ
كتاب كنوز أرسين لوبين
كتاب إنتقام ميت
كتاب جوهرة التاج
كتاب أرسين لوبين في موسكو
كتاب البيت الأسود
كتاب الإنذار
كتاب السهم القاتل
كتاب الخطر الأصفر
كتاب الجرائم الثلاثة
كتاب البرنس أرسين لوبين
كتاب السوق السوداء
كتاب المسلة الجوفاء
كتاب الرهان
كتاب الجثة المفقودة
كتاب ميزان العمل للكاتب أبو حامد

مجلة ميكي العدد 801
مجلة ميكي والسيارة
مجلة ميكي صاحب الفضل
مجلة ميكي العدد 871
مجلة ميكي العدد 870
مجلة ميكي العدد 812
مجلة ميكي العدد 796
مجلة ميكي العدد 783
مجلة ميكي العدد 771
مجلة ميكي العدد 752
مجلة ميكي العدد 738
مجلة ميكي العدد 730
مجلة ميكي العدد 691
مجلة ميكي العدد 689
مجلة ميكي العدد 688
مجلة ميكي العدد 639
مجلة ميكي العدد 580
مجلة ميكي العدد 566
مجلة ميكي العدد 564
مجلة ميكي العدد 336
مجلة خطوط العدد 706
كتاب الكافي في اللغة
كتاب ميزان الذهب في صناعة شعر العرب
كتاب تعلم لغة جديدة بسرعة وسهولة
كتاب الحروف اللاتينية لكتابة العربية
كتاب جواهر البلاغة
كتاب الإبداع الفكري والخصوصية الحضارية
كتاب اجتهاد الرسول وقضائه
كتاب صيحة نذير من فتنة التكفير
كتاب الشيخ المراغي والإصلاح الديني
كتاب الإصلاح بالإسلام
كتاب خطر النزعة التاريخية على ثوابت الإسلام
كتاب لتحيا اللغة العربية يسقط سيبويه
كتاب مفاتيح العلوم
كتاب السر في العين
كتاب السر ف القبعة
كتاب اللص الظريف
كتاب إسلامية المعرفة ماذا يعني
كتاب في الإصلاح الفكري والتربوي الإلهيات
كتاب مأزق المسيحية والعلمانية في أوروبا
كتاب الإسلام و

رواية مغامرات الكبيري فين
رواية حول العالم في ما يوما
كتاب تاريخ مصر من الفتح العثماني إلى قبيل الوقت الحاضر
رواية تجربة الدكتور أو
كتاب مصر في مطلع القرن التاسع عشر ١٨٠١–١٨١١م الجزء الثاني
كتاب أزمنة الثقافة الإيرانية معايشة من الداخل الجزء الأول
رواية الأمير والفقير
كتاب اصنام الكتابات
كتاب تاريخ الصلاة في الإسلام نسخة سالم الدليمي
كتاب مصر في مطلع القرن التاسع عشر الجزء الأول
كتاب ابو الهول
كتاب موسوعة مصر القديمة الجزء السابع عشر
رواية عشرون ألف فرصة تحت الماء
رواية شتاء وسط الجليد
رواية مغامرات توم سير
كتاب الصراع بين البورجوازية والإقطاع ١٧٨٩–١٨٤٨م المجلد الثالث
رواية في العام 2899
كتاب الصراع بين البورجوازية والإقطاع ١٧٨٩–١٨٤٨م المجلد الثاني
رواية رحلة على متن منطاد
كتاب الصراع بين البورجوازية والإقطاع ١٧٨٩–١٨٤٨م المجلد الأول
كتاب مصر في مطلع القرن التاسع عشر ١٨٠١–١٨١١م الجزء الثالث
كتاب المانيا النازية
رواية السيد ماريوس
كتاب مفهوم المنهج العلمي
كتاب فلسفة كارل بوبر
كتاب مشكلة العلوم الإنسانية
كتاب فلسفة العلم في القرن العشرين
كتاب ركائز في فلسفة السياسة
كتاب بحوث في تاريخ العل

مجلة ميكي العدد 131
كتاب مدارج السالكين
كتاب الحلقة المفقودة
كتاب الأمثال في القرآن
مجلة ميكي العدد 181
كتاب الفوائد
مجلة مواطن بطيء نموذجي
مجلة كل سنة وانت طيب
مجلة سوبر ميكي قرش الحظ
مجلة خطوط وميكي ماذا لو
مجلة خطوط وميكي ماذا حدث
مجلة خطوط وميكي دوت كوم
كتاب مراجع الشخصية للكاتب سيغموند فرويد
كتاب زاد المعاد في هدي خير العباد
كتاب ما فوق المبدأ واللذة للكاتب سيغموند فرويد
كتاب التحليل النفسي الهستيريا للكاتب سيغموند فرويد
كتاب علم نفس الجماهير للكاتب سيغموند فرويد
كتاب اليوم والحرام للكاتب سيغموند فرويد
كتاب الحلم وتأويله للكاتب سيغموند فرويد
كتاب القرآن يتحدى
كتاب العلمانية بين الغرب والاسلام
كتاب الغريزة والثقافة للكاتب سيغموند فرويد
كتاب لمرتين لإلياس أبو شبكة
كتاب غلواء لإلياس أبو شبكة
كتاب طاقات زهور
كتاب الحياة الجنسية للكاتب سيغموند فرويد
كتاب مستقبل وهم للكاتب سيغموند فرويد
كتاب إبليس في التحليل النفسي للكاتب سيغموند فرويد
كتاب التحليل النفسي لها الأطفال للكاتب سيغموند فرويد
كتاب أفكار لأزمنة الحرب والموت للكاتب سيغموند فرويد
كتاب التصعيد دروب الإبداع للكاتب سيغموند فرويد
ك

كتاب موسوعة الخطب المخبرية (2)
كتاب ملوك العرب
كتاب المهذب في شرح المائة النسائية
كتاب تهذيب صحيح ابن حبان (13)
كتاب تهذيب الأدب المفرد للبخاري
كتاب الإيمان بالملائكة وبين صفاتهم
كتاب دروس وعبر من حياة شهداء الثورة السورية
كتاب هل يعتبر الفراعنة بمصرع من سبقهم
كتاب الخلاصة في أصول التربية الإسلامية
كتاب تحقيق الهداية في النحو
كتاب الخلاصة في حكم سب الصحابة
كتاب الخلاصة في حكم الاستعانة بالكفار في القتال
كتاب الخلاصة في أحكام التمرس
كتاب الخلاصة في أحكام الانتحار
كتاب الميسر في الأحاديث القدسية
كتاب الإسلام بين جهل أبنائه وعجز علمائه
كتاب مشروعية المشاركة
كتاب صحيفة همام بن منبه
كتاب تهذيب الحرية أو الطوفان
كتاب الخلاصة في فقه الصلاة على المذهب الشافعي
كتاب مفهوم الولاء والبراء في القرآن والسنة
كتاب الأربعون الطبية
كتاب موسوعة الأسرة المسلمة
كتاب عائلة أونا
كتاب طيش الشباب
كتاب سطح خزنت أرجوكم
كتاب رحلة البحث عن الكنز
كتاب تحذير عاصفة
كتاب تبادلية والتر ديزني
كتاب صفات البيت المسلم
كتاب ترجمة الأئمة الأربعة
كتاب الأربعون الاجتماعية
كتاب الخلاصة في شرح الأربعين الشبابية
كتاب من قتل الابد

كتاب جون رينارد كينز
كتاب جون لوك
كتاب الدودة والثعبان
كتاب مأساة زينب
كتاب الفارس الجميل
كتاب إمبراطورية في المزاد
كتاب قصر الهودج
كتاب الارستقراطية مقدمة قصيرة جدا
كتاب نظرية الالعاب
كتاب الديناصورات مقدمة قصيرة جدا
كتاب اليوتوبيا مقدمة قصيرة جدا
كتاب رولان بارت
كتاب الانسانية مقدمة قصيرة جدا
كتاب علم الأحياء النهائي
كتاب التطور مقدمة قصيرة جدا
كتاب الدعائية والسريالية
كتاب توفيق مقدمة قصيرة جدا
كتاب النظرية النقدية
كتاب الحقيقة مقدمة قصيرة جدا
كتاب تاريخ الطب
الإيمان في صحيح أذكار النوم والاستيقاظ
كتاب الفلسفة الهندية
كتاب البوذية مقدمة قصيرة جدا
كتاب الكواكب مقدمة قصيرة جدا
كتاب علم الاحصاء
كتاب الخيال العلمي
كتاب نظرية الاختيار
كتاب فقه العيدين وأحكامها وفتاواها
كتاب أعمال صالحا لدخول الجنات
كتاب العناصر مقدمة قصيرة جدا
كتاب علم التشفير
كتاب جامع المنظومات في ضبط المتشابهات
كتاب من فَضِيلَةً مِنْ فَضَائِلِ النِّكَاح
كتاب من فضيلة من فضائل أذكار الصلاة
كتاب فقه الزكاة وأحكامها فتاويها
كتاب من وسية لتنال محبة الله
كتاب الوسائل الخمس لتغير لك ذنوبك
كتاب الجامع المتين لأخطاء وبدع الحج

كتاب عقد قبل سنت وجماعة من بين اور اسمه ابدى في الموت
كتاب زكاة بهيمة الأنعام السائمة في ضوء الكتاب والسنة
كتاب السلام في الإسلام
كتاب مجموعة رسائل الإمام الشهيد حسن البنا
كتاب قضيتنا ودعوتنا
كتاب خطابات حسن البنا الشاب إلى أبيه
كتاب الله في العقيدة الإسلامية
كتاب نظرات في كتاب الله
كتاب مذكرات الدعوة والداعية
كتاب نحو بعث جديد
كتاب نظرات في كتاب الله
كتاب ايام من حياتي
رواية المرأة مشكلة صنعها الرجل
رواية خلف أسوار العقل
كتاب الكلمة المقدسة
كتاب فقه الاستغفار
كتاب فقه الحياء
رواية الذين كانوا
رواية قلبي ليس للبيع
رواية الانفجار الحي
كتاب صلاتي حياتي
كتاب القصيدة الذهبية
كتاب رجل لكل العصور ابن تيمية
كتاب الأدب الضائع
كتاب صيحة تحذير وصرخة نذير
كتاب سيدى تحفة
كتاب دفع المال على مشروعية الحجاب الكامل
كتاب ضرورة محو الأمية التربوية
كتاب مالم تقرأه في الكتب عن أسرار المدير لأول مرة
كتاب علو الهمة نسخة اخري
كتاب حرمة أهل العلم
كتاب أدلة تحريم مصافحة الأجنبية النسخة الثانية
كتاب أدلة تحريم مصافحة الأجنبية
كتاب الإعلام بحرمة أهل العلم والإسلام
كتاب مناجاة المحسنين في الخلوات
كتاب تفجيرات لند

كتاب ذكريات صغيرة
كتاب حول التأصيل الإسلامي للعلوم الاجتماعية
كتاب دروس من محنة البوسنة والهرسك
كتاب قضية تحرير المراة
كتاب التطور والثبات في حياة البشرية
رواية الخنجر الفضي
رواية المؤامرة الخفية
كتاب أعماق الخطر
كتاب قراصنة الجو
كتاب عوامل السعة والمرونة في الشريعة الإسلامية للشيخ يوسف القرضاوي
كتاب المحنة في واقع الحركة الإسلامية المعاصرة للشيخ يوسف القرضاوي
كتاب النية والإخلاص للشيخ يوسف القرضاوي
كتاب الصحوة الإسلامية للشيخ يوسف القرضاوي
رواية الرمال المحرقة
كتاب المدخل لدراسة السنة النبوية للشيخ يوسف القرضاوي
كتاب عيون الهلاك
رواية ظل الأرض
رواية أشباح ولكن
كتاب الصراع الشيطاني
كتاب العين الثالثة
كتاب اخر العمالقة
كتاب أقوي رجل في العالم
كتاب الجاسوس الخارق
كتاب الجزيرة الذهبية
كتاب الرجل الثالث
كتاب الرجل الذي سرق الشمس
كتاب القنبلة لمحمود سالم
كتاب القوة الخفية
كتاب المدينة الصامتة
كتاب المغامرون الخمسة والرقم الناقص
كتاب الهدف لا شيء
كتاب 1=4 أو المجهول pdf
كتاب عميلة وبراكودا
كتاب سر الغواصة المجهولة
كتاب سر الطائرة المحطمة
كتاب رمال الموت
كتاب رقم 999
كتاب رصاصة واحدة تكفي
كتا

كتاب اسبينوزا لفؤاد زكريا
كراسة شروط مبادرة التمويل العقاري في ما الرسمية كاملة
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية جدا فهرس عام للكتاب للحافظ ابن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ ابن كثير
كتاب البداية والنهاية في للحافظ بن كثير
كتاب البداية والنهاية في للحافظ بن كثير
كتاب البداية والنهاية في للحافظ بن كثير
كتاب البداية والنهاية جدا للحافظ ابن كثير
رواية الغزاة
رواية الانفجار
رواية الخصم الرهيب
كتاب العدو الخارق
كتاب افاق الفلسفة
رواية الكهف
كتاب آراء نقدية في مشكلات الفكر والثقافة
كتاب تاريخ المشرق
كتاب الرق في الإسلام
كتاب زاد في التفسير المستوى الرابع
كتاب زاد في الفقه المستوى الرابع
كتاب زاد في العربية المستوى الرابع
كتاب زاد

كتاب جامع المسانيد والسنن جل للحافظ ابن كثير
كتاب جامع المسانيد والسنن جل للحافظ ابن كثير
كتاب لغز الرجل الازرق
كتاب لغز الزجاجة الصفراء
كتاب لغز البيضة المجوفة
كتاب لغز صواريخ الليل
كتاب لغز الحقيبة الدبلوماسية
كتاب لغز عين السمكة
كتاب لغز عصابة التزييف
كتاب لغز القبر الملكي
كتاب لغز المهرب الدولي
كتاب لغز الألغاز
كتاب لغز القصر الأخضر
كتاب لغز المنزل رقم في
كتاب لغز العقد المفقود
كتاب لغز البيت الخفي
كتاب سباق الموت
كتاب لغز الكوخ المحترق
كتاب الجاسوسة
كتاب جزيرة الحيتان
كتاب العميل
كتاب السرقة الإلكترونية
كتاب الرجل الحديدي
كتاب المعركة الأخيرة
كتاب انتقام القرصان
كتاب قطار منتصف الليل
كتاب لغز الهاربة الصغيرة
كتاب لغز الألف وجهpdf
كتاب لغز حمام السباحةpdf
كتاب لغز الحي الهادئpdf
كتاب لغز سر المجنونpdf
كتاب لغز العصا البيضاءpdf
كتاب لغز نور القمرpdf
كتاب لغز الرسالة المجهولةpdf
كتاب لغز فيلا المعاديpdf
كتاب لغز الخدعة المزدوجةpdf
كتاب لغز السرقة الثانيةpdf
كتاب لغز الراقص الإفريقيpdf
كتاب لغز الجاسوس الترانزستورpdf
كتاب لغز من الماضيpdf
كتاب لغز ثعلب الصحراءpdf
كتاب لغز الزلازل الغا

رواية سبعة مفاتيح بالبيت
رواية احزان الشيطان
رواية تايبي للكاتب احمد خالد توفيق
رواية ساحر اوز
رواية الافق المفقود
رواية التنين الاحمر
رواية افضل قصص الاشباح
رواية الرجل الخفي
تفسير سورة البقرة لابن كثير
تفسير سورة الفاتحة لابن كثير
تفسير سورة البقرة لابن كثير
كتاب تفسير سورة الفاتحة
رواية المهمة الإنتحارية pdf
رواية رجل بسبعة ارواح pdf
رواية البذور القاتله pdf
رواية صفقة السلاح pdf
رواية الجاسوس لمحمود سالم pdf
رواية وحش الأعماق pdf
رواية الخدعة لمحمود سالم pdf
رواية المهمة المستحيله pdf
رواية التمساح لمحمود سالم pdf
رواية قارئ الأفكار pdf
رواية رجل المستقبل pdf
رواية سمكة القرش الزرقاء pdf
رواية الرجل العنكبوت pdf
رواية الأموال السوداء pdf
رواية العدو المجهول pdf
رواية عدو في الفضاء pdf
رواية جزيرة الحيتان pdf
رواية الخدعة الأخيرة pdf
رواية عش النسر pdf
رواية سباق الموت pdf
رواية الدرابيل لمحمود سالم pdf
رواية جزر ساندويتش pdf
رواية سر المخطوفة pdf
رواية الخائن لمحمود سالم pdf
رواية العصفور لمحمود سالم pdf
رواية جبال كليمنجارو pdf
رواية نهايه الخائن pdf
رواية الدليل الأسود pdf
رواية 

كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب إلي الظل قوانين للحياة pdf
كتاب الرجل النبيل محمد رسول الله
كتاب حلية الوقار pdf
كتاب لأنك الله Because you are allah pdf
كتاب ليس من الضروري أن تتنفس pdf
كتاب سوار أمي pdf
كتاب سيكولوجيا الانحراف pdf
كتاب نصرة للشريعة pdf
كتاب هذا النفاق فاحذروا pdf
كتاب ندي تشتكي لعائشة pdf
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث المسانيد في
كتاب جامع الأحاديث الجامع الصغير جدا
كتاب جامع الأحاديث الجامع الصغير جدا
كتاب جامع الأحاديث الجامع الصغير جدا
القرآن الكريم الجزء الثلاثون ملون pdf
القرآن الكريم الجزء التاسع والعشرون ملون pdf
القرآن الكريم الجزء الثامن والعشرون ملون pdf
القرآن الكريم الجزء السابع والعشرون ملون pdf
القرآن الكريم الجزء السادس والعشرون ملون pdf
القرآن الكريم الجزء الخامس والعشرون ملون pdf
القرآن الكريم الجزء الرابع والعشرون ملون pdf
القرآن الكريم الجزء 

القرآن الكريم الجزء الثاني pdf
القرآن الكريم الجزء الأول pdf
رواية أيام مع دانيال
رواية في مملكة الأخوين
رواية اسمه أدهم
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب الرخصة الدولية لقيادة الحاسب الالى في ICDL pdf
كتاب الرخصة الدولية لقيادة الحاسب الالى ICDL pdf
كتاب تنمية الحساب الذهني السريع word
كتاب تنمية الحساب الذهني السريع pdf
كتاب تحليل وتصميم النظم pdf
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جدا
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب جمع الجوامع جل
كتاب ألف باء التصميم الداخلي pdf
كتاب المعايير الشرعية للمؤسسات المالية الإسلامية pdf
كتاب الضغط النفسي pdf
كتاب الفوتوشوب خطوة خطوة حتي الإحتراف pdf
كتاب نظم المعلومات الإدارية pdf
كتاب التوحد pdf
كتاب خفايا الدماغ pdf
كتاب تعليم أساسيات الحاسب الآلي pdf
كتاب أ

إمكانية رمضان 2021 الكويت-الفحيحيل
إمكانية رمضان 2021 الكويت-الفروانية
كتاب مع الآخرين
إمكانية رمضان 2021 أسبانيا-فالنسيا
إمكانية رمضان 2021 أسبانيا-ماربيا
إمكانية رمضان 2021 أسبانيا-غرناطة
إمكانية رمضان 2021 أسبانيا-برشلونة
إمكانية رمضان 2021 هولندا-ألكمار
إمكانية رمضان 2021 هولندا-لاهاي
إمكانية رمضان 2021 هولندا-روتردام
إمكانية رمضان 2021 هولندا-امستردام
إمكانية رمضان 2021 تونس-مدينة تونس
إمكانية رمضان 2021 تونس-قابس
إمكانية رمضان 2021 تونس-بنزرت
إمكانية رمضان 2021 تونس-اريانة
إمكانية رمضان 2021 فرنسا-تولوز
إمكانية رمضان 2021 فرنسا-باريس
إمكانية رمضان 2021 فرنسا-ليون
إمكانية رمضان 2021 ماليزيا-لنكاوي
إمكانية رمضان 2021 ماليزيا-كوالالمبور
إمكانية رمضان 2021 ماليزيا-سيلانجور
إمكانية رمضان 2021 ماليزيا-بينانج
كتاب تسهيل الفرائض
إمكانية رمضان 2021 أوكرانيا-دونيتسك
انسانية رمضان 2021 رمضان في الهند مدينة كوتشي [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة كيرلا [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان في الهند مدينة مومباي [امساكية رمضان 2021]
انسانية رمضان 2021 رمضان 

انسانية رمضان في السعودية مدينة الخرج لعام 1442 في 2021
انسانية رمضان في السعودية مدينة جيزان لعام 1442 في 2021
انسانية رمضان في السعودية مدينة حائل لعام 1442 في 2021
انسانية رمضان في السعودية مدينة الظهران لعام 1442 في 2021
انسانية رمضان في السعودية مدينة بيشة لعام 1442 في 2021
كتاب من أول نظرة
كتاب على اوراق شجر
كتاب كيمياء الفضيحة
كتاب ذلك المجهول
كتاب السيدة الأولى
كتاب مواقف الجزء الثاني
رواية الوحدة 731
رواية المرض السابع
رواية الشمس الأرجوانية
إمكانية رمضان في اليمن لعام 1442 في 2021
إمكانية رمضان في كندا في هاملتون لعام 1442 في 2021
إمكانية رمضان في كندا في أوتاوا لعام 1442 في 2021
إمكانية رمضان في كندا في فانكوفر لعام 1442 في 2021
إمكانية رمضان في كندا في الجاري لعام 1442 في 2021
إمكانية رمضان في كندا في مونتريال لعام 1442 في 2021
إمكانية رمضان في كندا في فكتوريا لعام 1442 في 2021
إمكانية رمضان في كندا في تورنتو لعام 1442 في 2021
كتاب النور والفراشة
كتاب بلاد الله خلق الله
كتاب ديانات أخرى
انسانية رمضان في السعودية مدينة الطائف لعام 1442 في 2021
انسانية رمضان تركيا مدينة انقرة

كتاب المعقول والمعقول في تراثنا الفكري
كتاب الشرق الفنان
كتاب ايام في امريكا
كتاب أسس التفكير العلمي
كتاب الكوميديا الأرضية
كتاب الثلاثية لنجيب محفوظ
كتاب أسطورة الأساطير في
كتاب أسطورة الأساطير في
كتاب أسطورة حامل الضياء في
كتاب أسطورة حامل الضياء في
كتاب أسطورة الفتاة الزرقاء
كتاب أسطورة معرض الرعب
كتاب أسطورة الطفيل
كتاب أسطورة أغنية الموت
كتاب أسطورة شبه مخيفة
كتاب أسطورة الطمطم
سورة الأنعام خط واضح في وتفسيرها
كتاب الله والنفس البشرية pdf
سورة المائدة خط واضح في وتفسيرها
رواية زوجة احمد
رواية كانت صعبة ومغرورة
سورة النساء خط واضح في وتفسيرها
كتاب وطني مصر
رواية ألف ليلة وليلة
رواية شهر العسل
رواية المسرحيات لنجيب محفوظ
رواية القرارا الاخير
رواية يا ابنتى لا تشعرينى معك
رواية همس النجوم
كتاب نموذج الشخصية الدينية في روايات نجيب محفوظ
سورة ال عمران خط واضح في وتفسيرها
كتاب HTML5 and CSS3
رواية السعادة ليس لها تاريخ
رواية الحب في رحاب الله
كتاب HTML and CSS 1st Edition
كتاب تعلم HTML5 في سطور
رواية النظارة السوداء
رواية وعاشت بين أصابعه
رواية حتى لا يطير الدخان
رواية على لوز لنجيب مح

كتاب توريخوس وكريسيما
كتاب هنري الخامس
كتاب ثنائية هنري الرابع
كتاب هنري السادس ج1&ج2
كتاب مأساة كريملان
كتاب كلوديوس شكسبير
كتاب جعجعة بدون طحن
كتاب المسيخ الدجال
رواية الرابح يبقى وحيدا
رواية إحدى عشر دقيقة
رواية دليل فارس النور
كتاب محمد صلى الله عليه وسلم
كتاب الجاسوسة للكاتب باولو كويلو
كتاب مكتوب للكاتب باولو كويلو
كتاب السيميائي ساحر الصحراء
كتاب كالنهر الذى يجري
كتاب أوراق محارب الضوء
كتاب مخطوطة وجدت في عكرا
كتاب رجل تحت الصفر
كتاب فتيات فاليري
كتاب الشيخ الهندي
كتاب الشمعدان الحديدي
كتاب السندباد البحري
كتاب السنجاب الصغير
كتاب السعيد حسن
كتاب الديك الظريف
كتاب الدجاجة الصغيرة الحمراء
كتاب الحمار القارئ
كتاب التاجر مرمر
كتاب البيت الجديد
كتاب الأميرة القاسية
كتاب الأمير مشمش
كتاب مصطلح الحديث
كتاب القواعد المثلى في صفات الله وأسمائه الحسنى
كتاب قواعد في الإملاء
كتاب أناشيد الإثم والبراءة
كتاب شرح العقيدة الواسطية
كتاب اهدنا الداء والدواء
كتاب تساؤلات قلوب حائرة
كتاب رحلة المشتاق للحج والعمرة
كتاب من الطارق أنا رمضان
كتاب المهاجرون الجدد
كتاب هبي تاريخ الإيمان
كتاب نقطة رجوع
ك

كتاب إدارة عصر البطالة
كتاب إعلان عن جريمة
كتاب ساحر النساء
كتاب المرأة في عصر الديمقراطية
كتاب مملكة جهنم والخمر
كتاب حِكَم النبي مُحمَّد
كتاب اعترافات تولستوي
كتاب قضية ستايلز الغامضة
كتاب إنجيل تولستوي وديانته
كتاب يوليوس قيصر
كتاب الجريمة النائمة
كتاب ليل لا ينتهى
كتاب جثة فى المكتبة
كتاب الأسد الطائر
كتاب هملت للكاتب ويليام شكسبير
كتاب أكبر للكاتب ويليام شكسبير
كتاب عطيل للكاتب ويليام شكسبير
كتاب البيت المائل
كتاب ضجة فارغة
كتاب ترويض النمرة
كتاب تاجر البندقية
كتاب ذكريات أجاثا كريستي
كتاب الملك لير
كتاب العبرة بالخواتيم
كتاب مناجاة أرواح
كتاب رجل بلا وجه
كتاب رمل وزبد
كتاب دمعة وابتسامة
كتاب العواصف للكاتب جبران خليل جبران
كتاب البدائع والطرائف
كتاب الضحية العاشرة
كتاب الأرواح المتمردة
كتاب الأجنحة المتكسرة
كتاب آلهة الأرض
كتاب الأربعة الكبار
كتاب كليوباترا ملكة مصر
كتاب مصر والحضارة الإسلامية
كتاب الإسلام في الحبشة
كتاب دليل قراءة الى تاريخ الكنيسة
كتاب هيرودوت لا جينيفر تي روبرتس
كتاب الجريمة المعقدة
كتاب الأرنب والصياد
كتاب الأرنب العاصي
كتاب الأرنب الذكي
كتاب ابن جبير في مصر 

رواية حرب الاندال
رواية عندما يصبح الانتقام عدالة الجزء الثالث
قصة الخطر
قصة مغامرة كوبر بيتميز
قصة مغامرة روسكوم أولد بليس
قصة مغامرة النبيل الأعزب
قصة لغز وادي بوسكورة
قصة مغامرة إبهام المهندس
كتاب قوة التركيز وتحسين الذاكرة
قصة مغامرة العميل المرموق
قصة مغامرة الجوهرة الزرقاء
قصة بذور البرتقال الخمس
كتاب اكستازي أن يوم
كتاب فلسطين التاريخ المصور
كتاب الأوبئة والتاريخ المرض والقوة والإمبريالية
كتاب فلسفة التاريخ
كتاب عظماء ومشاهير معاقون غيروا مجرى التاريخ
كتاب من خطأ وأسلوبا مرفوضا في تربية الأطفال
كتاب فن إدارة المواقف الجزء الأول
كتاب أينشتين والنسبية
كتاب كيف تكون كاتباً بارعاً
كتاب من شارع النجاح
قصة المغامرة الأخيرة
قصة مغامرة تشارلز أوجست ميلفيرتون
قصة مغامرة الرجال الراقصين
قصة مغامرة العصابة الرقباء
كتاب تاريخ مصر والسودان الحديث والمعاصر
كتاب الإسلام والعربية في السودان
كتاب السودان في البرلمان المصري
كتاب جماعات غرب افريقيا
كتاب حياة الشرق دوله وشعوبه وماضيه وحاضره
كتاب مصر والسودان كفاح مشترك
كتاب وادي النيل مصر والسودان
كتاب مياه النيل الوعد والوعيد
كتاب السودان دراسة جغ

انسانية رمضان 2020 لعام 1441 في [امساكية رمضان 2020]
كتاب ابدأ بالأهم ولو كان صعبا
كتاب محمد نبي لزماننا
كتاب للرجال فقط
كتاب اول ما ساعة للكاتب جوش كوفمان
تحميل سورة الكهف خط كبير واضح
قصة ورواية بلد العميان pdf احمد خالد توفيق
كتاب أيقظ قواك الخفية أنتوني روبنز
كتاب قوة العادات تشارلز دوي
كتاب قوة التفكير وأثاره على حياتك ابراهيم الفقى
كتاب كيف تكسب الأصدقاء وتؤثر في الناس
كتاب لغات الحب الخمس جاري شابمان
القرآن الكريم باللغة الصينية 古蘭經》中文
كتاب من الذي حرك قطعة الجبن الخاصة بي
كتاب قوة التحكم بالذات ابراهيم الفقي
كتاب إدارة الوقت ابراهيم الفقي
كتاب قوة عقلك الباطن جوزيف ميرفي
كتاب الأب الغني والأب الفقير
القرآن الكريم باللغة التركية Kur’an-ı Kerim Türkçe
القرآن الكريم باللغة الهندية पवित्र कुरान हिंदी में
كتاب القرآن الكريم باللغة الفارسية كتاب قرآن درهم با ترجمه فارسي
القرآن الكريم باللغة الرومانية Sfântul Coran في limba română
القرآن الكريم باللغة الإيطالية أن Sacro Corano في lingua italiana
كتاب جدد حياتك الشيخ محمد الغزالي
كتاب أحترف فن الفراسة ابراهيم الفقي
كتاب أسرار عقل الملي

In [5]:
df.head()

Author                                  Title  \
0  الكاتب هارون يحيىالكاتب هارون يحيى  كتاب هدم نظرية التطور في عشرين سؤالا    
1  الكاتب هارون يحيىالكاتب هارون يحيى                        كتاب فن التأمل    
2  الكاتب هارون يحيىالكاتب هارون يحيى                    كتاب الأمم البائدة    
3  الكاتب هارون يحيىالكاتب هارون يحيى                كتاب المعجزات القرآنية    
4  الكاتب هارون يحيىالكاتب هارون يحيى                     كتاب خديعة التطور    

                                        Link for PDF             Category  \
0  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
1  https://www.arab-books.com/books/%d9%83%d8%aa%...     كتب الأدب العربي   
2  https://www.arab-books.com/books/%d9%83%d8%aa%...       الثقافة العامة   
3  https://www.arab-books.com/books/%d9%83%d8%aa%...          كتب اسلامية   
4  https://www.arab-books.com/books/%d9%83%d8%aa%...  كتب الفلسفة والمنطق   

   Number Of Pages  
0              154  
1               68  
2              162  
3               99  
4              258

In [6]:
# Check For Null Values
df.isnull()

Author  Title  Link for PDF  Category  Number Of Pages
0      False  False         False     False            False
1      False  False         False     False            False
2      False  False         False     False            False
3      False  False         False     False            False
4      False  False         False     False            False
...      ...    ...           ...       ...              ...
5935   False  False         False     False            False
5936   False  False         False     False            False
5937   False  False         False     False            False
5938   False  False         False     False            False
5939   False  False         False     False            False

[5940 rows x 5 columns]

In [7]:
df.isnull().sum()

Author             251
Title                0
Link for PDF         0
Category             0
Number Of Pages      0
dtype: int64

In [8]:
df.describe()

Number Of Pages
count      5940.000000
mean        183.487542
std         185.662309
min           1.000000
25%          52.000000
50%         126.000000
75%         242.000000
max         992.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5940 entries, 0 to 5939
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Author           5689 non-null   object
 1   Title            5940 non-null   object
 2   Link for PDF     5940 non-null   object
 3   Category         5940 non-null   object
 4   Number Of Pages  5940 non-null   int64 
dtypes: int64(1), object(4)
memory usage: 232.2+ KB


In [10]:
pd.crosstab(df['Author'], df['Title'], margins=True)

Title                                               15 فضيلة من فضائل ليلة القدر   \
Author                                                                              
Andy Harris                                                                     0   
David Graeber                                                                   0   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...                              0   
David H. Weiss                                                                  0   
Steven Pinker                                                                   0   
...                                                                           ...   
يوسف إدريس                                                                      0   
يوسف العش                                                                       0   
يوسف كرم                                                                        0   
يوسي إم هانيماكي                                                                0   
All                                                                             1   

Title                                               Corán traducido al español  – القران نسخة اسبانية  \
Author                                                                                                  
Andy Harris                                                                                         0   
David Graeber                                                                                       0   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...                                                  0   
David H. Weiss                                                                                      0   
Steven Pinker                                                                                       0   
...                                                                                               ...   
يوسف إدريس                                                                                          0   
يوسف العش                                                                                           0   
يوسف كرم                                                                                            0   
يوسي إم هانيماكي                                                                                    0   
All                                                                                                 1   

Title                                               The book of”Bullshit Jobs”   \
Author                                                                            
Andy Harris                                                                   0   
David Graeber                                                                 1   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...                            0   
David H. Weiss                                                                0   
Steven Pinker                                                                 0   
...                                                                         ...   
يوسف إدريس                                                                    0   
يوسف العش                                                                     0   
يوسف كرم                                                                      0   
يوسي إم هانيماكي                                                              0   
All                                                                           1   

Title                                               bullshit jobs   \
Author                                                               
Andy Harris                                                      0   
David Graeber                                                    1   
David Graeberالكاتب أحمد بن عبد الحليم بن عبد ا...               0   
David H. Weiss                                                   0   
Steven Pinker               

In [11]:
# Clean DataSet And Replace Null Values
df.dropna(inplace=True)
df = df.drop(columns='Link for PDF')
df = df.drop(columns='Number Of Pages')

In [12]:
df.describe()

Author               Title     Category
count              5689                5689         5689
unique              613                5588           75
top     أحمد خالد توفيق  كتاب نهاية العالم   كتب اسلامية
freq                320                   3         1294

In [13]:
from sklearn.model_selection import train_test_split

In [92]:
author = df['Author']
title = df['Title']
X = (author)+(title)
y= df['Category']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [93]:
y_train.value_counts(), y_test.value_counts()

(كتب اسلامية         1027
 روايات بوليسية       493
 كتب روايات عربية     456
 كتب الأدب العربي     347
 العقيدة              306
                     ... 
 كتب تاريخ اوروبا       1
 الفن                   1
 علوم الحاسب            1
 علوم اللغة             1
 الرياضيات              1
 Name: Category, Length: 72, dtype: int64,
 كتب اسلامية                          267
 روايات بوليسية                       117
 كتب روايات عربية                     112
 كتب الأدب العربي                      92
 العقيدة                               78
 كتب الأطفال                           51
 كتب الروايات العالمية المترجمة        40
 الأدب                                 33
 الثقافة العامة                        30
 كتب التنمية الذاتية                   27
 القرآن الكريم                         21
 كتب التاريخ                           20
 كتب الأدب العالمي المترجم             20
 كتب التاريخ الحديث                    19
 كتب علم النفس                         19
 كتب القصص القصيرة المترجمة            16

In [94]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

In [95]:
text_clf_svm = Pipeline([('tfidf',TfidfVectorizer()),
                       ('svc', LinearSVC()),])

In [96]:
text_clf_svm.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [97]:
predictions = text_clf_svm.predict(X_test)

In [98]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predictions))

[[ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0 17 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  0  0  0]]


In [99]:
print(metrics.accuracy_score(y_test, predictions))

0.7521968365553603


In [100]:
text_clf_nb = Pipeline([('tfidf',TfidfVectorizer()),
                       ('clf', MultinomialNB()),])

In [101]:
text_clf_nb.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [102]:
predictions = text_clf_nb.predict(X_test)

In [103]:
print(metrics.confusion_matrix(y_test, predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 7 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [104]:
print(metrics.accuracy_score(y_test, predictions))

0.624780316344464


In [105]:
from sklearn.ensemble import RandomForestClassifier

In [106]:
text_clf_rf = Pipeline([('tfidf',TfidfVectorizer()),
                       ('svc',RandomForestClassifier(n_estimators=1800, random_state=0)),])

In [107]:
text_clf_rf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('svc',
                 RandomForestClassifier(n_estimators=1800, random_state=0))])

In [108]:
predictions = text_clf_rf.predict(X_test)

In [109]:
print(metrics.confusion_matrix(y_test, predictions))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 16 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  0]]


In [110]:
print(metrics.accuracy_score(y_test, predictions))

0.7530755711775043


In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
text_clf_lg = Pipeline([('tfidf',TfidfVectorizer()),
                       ('lg',LogisticRegression(random_state=0)),])

In [113]:
text_clf_lg.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('lg', LogisticRegression(random_state=0))])

In [114]:
predictions = text_clf_lg.predict(X_test)

In [115]:
print(metrics.confusion_matrix(y_test, predictions))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [116]:
print(metrics.accuracy_score(y_test, predictions))

0.7240773286467487


In [137]:
from sklearn.neighbors import KNeighborsClassifier
text_clf_knn = Pipeline([('tfidf',TfidfVectorizer()),
                       ('knn',KNeighborsClassifier(n_neighbors=4)),])

In [138]:
text_clf_knn.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('knn', KNeighborsClassifier(n_neighbors=4))])

In [139]:
prediction = text_clf_knn.predict(X_test)

In [140]:
print(metrics.confusion_matrix(y_test, predictions))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [141]:
print(metrics.accuracy_score(y_test, predictions))

0.7240773286467487
